/**
 * Seed script — run from the backend/ directory:
 *   node seed.js
 *
 * Category IDs:
 *   1-Internship  2-Scholarship  3-Hackathon  4-Research
 *   5-Course      6-Exchange     7-Competition 8-Workshop
 */
require('dotenv').config({ path: require('path').resolve(__dirname, '.env') });
const mongoose = require('mongoose');
const bcrypt   = require('bcrypt');

const User             = require('./models/User');
const Opportunity      = require('./models/Opportunity');
const SavedOpportunity = require('./models/SavedOpportunity');
const Notification     = require('./models/Notification');

const future = days => new Date(Date.now() + days * 86_400_000);

async function seed() {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✔ Connected to MongoDB');

    await Promise.all([
        User.deleteMany({}), Opportunity.deleteMany({}),
        SavedOpportunity.deleteMany({}), Notification.deleteMany({}),
    ]);
    console.log('✔ Cleared existing data');

    const [admin, student] = await User.insertMany([
        { user_name: 'admin',        email: 'admin@campus.edu',     password_hash: await bcrypt.hash('admin123',   10), role_id: 1, dept_id: 1, dept_name: 'Computer Science' },
        { user_name: 'demo_student', email: 'student@seecs.edu.pk', password_hash: await bcrypt.hash('student123', 10), role_id: 2, dept_id: 1, dept_name: 'Computer Science' },
    ]);
    const by = admin._id;
    console.log('✔ Created users (admin + demo_student)');

    // ── INTERNSHIPS (cat 1) ──────────────────────────────────────────────────
    const internships = [
        { title: 'Google Summer of Code 2025', organization: 'Google', description: 'GSoC connects students with open-source organisations for a 3-month paid coding project. Mentored by experienced engineers, you build real portfolio projects on GitHub used by millions globally.', category_id: 1, category_name: 'Internship', dept_id: 1, dept_name: 'Computer Science', deadline: future(28), opp_mode: 'remote', location: 'Remote (Global)', is_paid: true, stipend: 'USD 3,000 – 6,600 (lump sum)', duration: '3 months (May – Aug)', required_skills: ['Git', 'Python / C++ / JavaScript', 'Open Source'], eligibility: 'Enrolled university students aged 18+. At least one open-source contribution.', application_link: 'https://summerofcode.withgoogle.com', tags: ['open-source', 'coding', 'mentorship', 'remote'], posted_by: by },
        { title: 'Microsoft Explore Internship', organization: 'Microsoft', description: 'A 12-week internship for freshmen and sophomores rotating across software engineering and programme management. Interns ship real features in Microsoft 365 or Azure, attend leadership Q&As, and complete a cross-team design challenge.', category_id: 1, category_name: 'Internship', dept_id: 1, dept_name: 'Computer Science', deadline: future(35), opp_mode: 'hybrid', location: 'Redmond, WA (Hybrid)', is_paid: true, stipend: 'USD 7,000/month + relocation', duration: '12 weeks (June – Aug)', required_skills: ['C#', 'Azure', 'Data Structures', 'Algorithms'], eligibility: 'Freshman or sophomore in CS/related. CGPA ≥ 3.2.', application_link: 'https://careers.microsoft.com', tags: ['cloud', 'product', 'global'], posted_by: by },
        { title: 'Systems Limited Graduate Internship', organization: 'Systems Limited', description: 'Pakistan\'s largest IT exporter embeds interns in product teams building fintech, ERP, and digital-transformation solutions for global clients. Structured programme with mentorship, tech talks, and a pre-placement offer for top performers.', category_id: 1, category_name: 'Internship', dept_id: 1, dept_name: 'Computer Science', deadline: future(18), opp_mode: 'on-campus', location: 'Lahore, Pakistan', is_paid: true, stipend: 'PKR 40,000/month', duration: '3 months', required_skills: ['Java', 'Spring Boot', 'SQL', 'REST APIs'], eligibility: 'Final-year or recently graduated BS CS/SE/IT. CGPA ≥ 3.0.', application_link: 'https://www.systemsltd.com/careers', tags: ['fintech', 'enterprise', 'pre-placement'], posted_by: by },
        { title: 'Careem Product & Engineering Internship', organization: 'Careem (Uber)', description: 'Join the super-app used by 50 million users. Engineering interns join squads building ride-hailing, food, or fintech features. Real sprint planning, code reviews, and a project demo to VP Engineering at the end.', category_id: 1, category_name: 'Internship', dept_id: 1, dept_name: 'Computer Science', deadline: future(21), opp_mode: 'hybrid', location: 'Karachi / Remote', is_paid: true, stipend: 'PKR 65,000/month', duration: '3 months', required_skills: ['Kotlin', 'Node.js', 'Microservices', 'AWS'], eligibility: 'Penultimate or final year CS/SE. Mobile or backend experience required.', application_link: 'https://careem.com/careers', tags: ['super-app', 'mobile', 'backend', 'MENA'], posted_by: by },
        { title: 'Arbisoft Summer Internship', organization: 'Arbisoft', description: 'Work on US-based client SaaS products with senior engineers at one of Pakistan\'s fastest-growing software companies. Bi-weekly learning sessions and a demo day at the end. Strong performers receive return offers.', category_id: 1, category_name: 'Internship', dept_id: 1, dept_name: 'Computer Science', deadline: future(14), opp_mode: 'hybrid', location: 'Lahore, Pakistan', is_paid: true, stipend: 'PKR 35,000/month', duration: '2 months (June – July)', required_skills: ['React', 'Django', 'Python', 'PostgreSQL'], eligibility: '3rd or 4th year CS/SE. One deployed web project required.', application_link: 'https://arbisoft.com/careers', tags: ['web-development', 'startup', 'client-work'], posted_by: by },
        { title: 'Jazz Digital Innovation Internship', organization: 'Jazz (Veon)', description: 'Pakistan\'s largest telecom is hiring CS/EE interns for its Digital & AI division. Interns build predictive churn models, network analytics dashboards, and AI-driven customer care tools. Exposure to petabyte-scale real-time pipelines.', category_id: 1, category_name: 'Internship', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(12), opp_mode: 'on-campus', location: 'Islamabad, Pakistan', is_paid: true, stipend: 'PKR 45,000/month', duration: '6 weeks', required_skills: ['Python', 'SQL', 'Machine Learning', 'Data Analytics'], eligibility: '3rd/4th year EE, CS, or DS students.', application_link: 'https://jazz.com.pk/careers', tags: ['telecom', 'AI', 'data', 'Pakistan'], posted_by: by },
    ];

    // ── SCHOLARSHIPS (cat 2) ─────────────────────────────────────────────────
    const scholarships = [
        { title: 'HEC Need-Based Scholarship 2025–26', organization: 'Higher Education Commission Pakistan', description: 'Financial assistance for deserving students from low-income families enrolled in recognised Pakistani HEIs. Covers tuition fees, hostel charges, and a monthly stipend for up to 4 years of undergraduate study.', category_id: 2, category_name: 'Scholarship', dept_id: 1, dept_name: 'Computer Science', deadline: future(45), opp_mode: 'on-campus', location: 'Pakistan (All HEIs)', is_paid: true, stipend: 'PKR 60,000/year + tuition waiver', duration: 'Up to 4 years (renewable)', required_skills: [], eligibility: 'Pakistani BS students. Family income < PKR 45,000/month. CGPA ≥ 2.5.', application_link: 'https://www.hec.gov.pk/needbased', tags: ['need-based', 'undergraduate', 'government'], posted_by: by },
        { title: 'DAAD Scholarship — Study in Germany 2026', organization: 'DAAD (German Academic Exchange Service)', description: 'Full scholarship for outstanding Pakistani students pursuing Master\'s or PhD at top German universities. Covers tuition, EUR 934/month living allowance, health insurance, travel allowance, and German language courses.', category_id: 2, category_name: 'Scholarship', dept_id: 1, dept_name: 'Computer Science', deadline: future(60), opp_mode: 'on-campus', location: 'Germany', is_paid: true, stipend: 'EUR 934/month + extras', duration: '1–2 years (Master\'s) / 3 years (PhD)', required_skills: ['Academic Excellence', 'Research Proposal'], eligibility: 'BS graduates CGPA ≥ 3.0. Max age 32 (Master\'s) / 35 (PhD).', application_link: 'https://www.daad.de/en', tags: ['Germany', 'masters', 'PhD', 'fully-funded'], posted_by: by },
        { title: 'Commonwealth Scholarship — United Kingdom', organization: 'Commonwealth Scholarship Commission', description: 'Fully funded scholarship for Commonwealth citizens to pursue Master\'s and PhD degrees at UK universities. Includes tuition, GBP 1,236/month allowance, return airfare, and thesis grant.', category_id: 2, category_name: 'Scholarship', dept_id: 2, dept_name: 'Business Administration', deadline: future(55), opp_mode: 'on-campus', location: 'United Kingdom', is_paid: true, stipend: 'GBP 1,236/month + tuition + airfare', duration: '1 year (Master\'s) / 3 years (PhD)', required_skills: ['First/Upper-Second Class Degree', 'IELTS 6.5+'], eligibility: 'Pakistani citizens. Upper-second or first class Bachelor\'s.', application_link: 'https://www.hec.gov.pk/commonwealth', tags: ['UK', 'fully-funded', 'development', 'masters'], posted_by: by },
        { title: 'Aga Khan Foundation International Scholarship', organization: 'Aga Khan Foundation', description: 'Postgraduate scholarships for outstanding students from developing countries with no other means of funding. Structured as 50% grant + 50% loan for Master\'s and PhD programs worldwide.', category_id: 2, category_name: 'Scholarship', dept_id: 2, dept_name: 'Business Administration', deadline: future(50), opp_mode: 'on-campus', location: 'International', is_paid: true, stipend: 'Partial grant (50%) + 50% loan', duration: 'Duration of postgraduate program', required_skills: ['Academic Excellence', 'Community Service'], eligibility: 'Pakistani citizens. Outstanding merit and genuine financial need.', application_link: 'https://www.akdn.org/AKF_Scholarships', tags: ['postgraduate', 'merit-need', 'international'], posted_by: by },
        { title: 'Teach For Pakistan Fellowship', organization: 'Teach For Pakistan', description: 'Two-year Fellowship placing talented graduates as full-time teachers in under-resourced schools. Includes intensive leadership training, PKR 45,000/month stipend, and an alumni network of Pakistan\'s most impactful professionals.', category_id: 2, category_name: 'Scholarship', dept_id: 2, dept_name: 'Business Administration', deadline: future(42), opp_mode: 'on-campus', location: 'Karachi / Lahore / Islamabad', is_paid: true, stipend: 'PKR 45,000/month', duration: '2 years', required_skills: ['Communication', 'Leadership', 'Resilience'], eligibility: 'Graduates (within 3 years). Any discipline. CGPA ≥ 3.0.', application_link: 'https://teachforpakistan.org/fellowship', tags: ['fellowship', 'education', 'social-impact', 'leadership'], posted_by: by },
        { title: 'Atlas Corps Global Leadership Fellowship', organization: 'Atlas Corps (Washington DC)', description: 'Atlas Corps places skilled leaders from 100+ countries at US nonprofits for 12–18 month paid fellowships. Past Pakistani fellows served at Amnesty International, CARE, and Brookings. Includes health insurance and global alumni network.', category_id: 2, category_name: 'Scholarship', dept_id: 2, dept_name: 'Business Administration', deadline: future(50), opp_mode: 'on-campus', location: 'Washington DC, USA', is_paid: true, stipend: 'USD 1,500/month + health insurance', duration: '12–18 months', required_skills: ['Leadership', 'English Proficiency', 'Social Sector Experience'], eligibility: 'Graduates aged 21–35. Min 2 years experience in social sector.', application_link: 'https://atlascorps.org/apply', tags: ['fellowship', 'USA', 'nonprofit', 'leadership'], posted_by: by },
    ];

    // ── HACKATHONS (cat 3) ───────────────────────────────────────────────────
    const hackathons = [
        { title: 'NUST AI Hackathon — Build the Future', organization: 'NUST Centre for Artificial Intelligence', description: '48-hour AI hackathon with tracks in Healthcare, Climate, Education, and FinTech. Teams of 2–4 students compete for a PKR 500,000 prize pool and mentorship from NUST industry partners.', category_id: 3, category_name: 'Hackathon', dept_id: 1, dept_name: 'Computer Science', deadline: future(9), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: true, stipend: 'Prize Pool: PKR 500,000', duration: '48 hours', required_skills: ['Python', 'Machine Learning', 'TensorFlow / PyTorch'], eligibility: 'All enrolled NUST students. Teams of 2–4.', application_link: '', tags: ['AI', 'machine-learning', '48-hour', 'prize'], posted_by: by },
        { title: 'Telenor Digital Innovation Challenge', organization: 'Telenor Pakistan', description: 'Annual challenge for university teams to pitch digital solutions for connectivity and inclusion. Online qualifying → top 10 fly to Islamabad finals. Winner gets PKR 300,000 + internship offer.', category_id: 3, category_name: 'Hackathon', dept_id: 1, dept_name: 'Computer Science', deadline: future(22), opp_mode: 'hybrid', location: 'Islamabad (Final) / Online', is_paid: true, stipend: 'PKR 300,000 + internship offer', duration: '3 weeks online + 2-day final', required_skills: ['Product Design', 'Business Modeling', 'Prototyping'], eligibility: 'University students from any discipline. Teams of 3.', application_link: 'https://telenor.com.pk/innovation-challenge', tags: ['telecom', 'innovation', 'startup', 'prize'], posted_by: by },
        { title: 'GitHub Copilot Hackathon — AI-Assisted Dev', organization: 'GitHub', description: 'Build any project using GitHub Copilot and submit your repo. Judged on code quality, innovation, and real-world impact. Monthly rolling submissions.', category_id: 3, category_name: 'Hackathon', dept_id: 1, dept_name: 'Computer Science', deadline: future(30), opp_mode: 'remote', location: 'Remote (Global)', is_paid: true, stipend: 'USD 5,000 monthly prize', duration: 'Rolling monthly', required_skills: ['Any Language', 'GitHub', 'GitHub Copilot'], eligibility: 'Any developer worldwide. Individual or team (max 4).', application_link: 'https://github.com/hackathon', tags: ['AI', 'GitHub', 'open-source', 'remote'], posted_by: by },
        { title: 'NASA Space Apps Challenge — Pakistan', organization: 'NASA / SUPARCO', description: 'The world\'s largest hackathon. Teams solve real space and Earth science challenges using NASA open data. Local winners go to NASA\'s global judging. No aerospace background required.', category_id: 3, category_name: 'Hackathon', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(16), opp_mode: 'on-campus', location: 'Islamabad / Lahore / Karachi', is_paid: false, stipend: 'Global winner: NASA facility visit', duration: '2 days (48 hours)', required_skills: ['Data Visualisation', 'Python or JS', 'Creative Problem Solving'], eligibility: 'Any university student. Teams of 1–6.', application_link: 'https://www.spaceappschallenge.org', tags: ['NASA', 'space', 'data', 'global'], posted_by: by },
        { title: 'HackNUST — Inter-University Hackathon', organization: 'NUST ACM Student Chapter', description: '36-hour inter-university hackathon. Participants compete in Fintech, Smart Cities, EdTech, and Health tracks. Mentors from Careem, Telenor, and NUST faculty on-site throughout.', category_id: 3, category_name: 'Hackathon', dept_id: 1, dept_name: 'Computer Science', deadline: future(11), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: true, stipend: 'PKR 150,000 total prizes', duration: '36 hours', required_skills: ['Any Tech Stack', 'Rapid Prototyping', 'Teamwork'], eligibility: 'Open to all Pakistani university students. Teams of 3–5.', application_link: '', tags: ['inter-university', 'fintech', 'EdTech', 'NUST'], posted_by: by },
        { title: 'Meta Open Source Hackathon', organization: 'Meta (Facebook)', description: 'Build projects using Meta\'s open-source stack: React, PyTorch, LLAMA, or Llama Index. Evaluated by Meta engineers. Top projects are featured on Meta\'s blog and developers win gift cards.', category_id: 3, category_name: 'Hackathon', dept_id: 1, dept_name: 'Computer Science', deadline: future(25), opp_mode: 'remote', location: 'Remote (Global)', is_paid: true, stipend: 'USD 2,000 gift cards + Meta swag', duration: '4 weeks (rolling submissions)', required_skills: ['React', 'PyTorch', 'LLMs', 'Open Source'], eligibility: 'University students worldwide. Individual or team (max 3).', application_link: 'https://developers.facebook.com/community', tags: ['Meta', 'React', 'AI', 'LLM'], posted_by: by },
    ];

    // ── RESEARCH (cat 4) ─────────────────────────────────────────────────────
    const research = [
        { title: 'NUST AI Lab Research Assistantship', organization: 'NUST Artificial Intelligence Research Centre', description: 'RAs join NLP, Computer Vision, and RL projects, assist with literature reviews, run experiments, and co-author papers targeting NeurIPS, ICML, and CVPR.', category_id: 4, category_name: 'Research', dept_id: 1, dept_name: 'Computer Science', deadline: future(17), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: true, stipend: 'PKR 25,000/month', duration: '6 months (renewable)', required_skills: ['Python', 'PyTorch', 'Machine Learning', 'Research Writing'], eligibility: 'BS 3rd/4th year or MS students in CS/DS/EE. CGPA ≥ 3.2.', application_link: '', tags: ['AI', 'NLP', 'computer-vision', 'publication', 'lab'], posted_by: by },
        { title: 'UNESCO Youth Research Grant — Digital Futures', organization: 'UNESCO Pakistan', description: 'Grants of up to USD 5,000 for student-led research on Digital Futures themes: digital inclusion, AI ethics, online misinformation, and digital skills gaps. Findings may appear in UNESCO global reports.', category_id: 4, category_name: 'Research', dept_id: 4, dept_name: 'Media Studies', deadline: future(38), opp_mode: 'remote', location: 'Remote / Pakistan', is_paid: true, stipend: 'Up to USD 5,000 research grant', duration: '6 months', required_skills: ['Research Methodology', 'Data Analysis', 'Academic Writing'], eligibility: 'Pakistani students aged 18–30. Individual or teams of 2.', application_link: 'https://www.unesco.org/pakistan', tags: ['UNESCO', 'social-research', 'digital', 'grant'], posted_by: by },
        { title: 'NUST Energy Research Lab RA — Renewable Energy', organization: 'NUST School of Electrical Engineering', description: 'RAs work on solar micro-grids, battery storage optimisation, and smart grid communication. Involves MATLAB simulations, lab experiments, and IEEE Transactions-level publications.', category_id: 4, category_name: 'Research', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(20), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: true, stipend: 'PKR 20,000/month', duration: '6 months', required_skills: ['MATLAB', 'Power Systems', 'Circuit Analysis', 'LaTeX'], eligibility: 'BS 3rd/4th year or MS EE students. CGPA ≥ 3.0.', application_link: '', tags: ['renewable-energy', 'IEEE', 'simulation', 'lab'], posted_by: by },
        { title: 'LUMS Centre for Economic Research — RA', organization: 'LUMS (Lahore University of Management Sciences)', description: 'Undergraduate RAs assist on empirical micro-economics, development economics, and labour market research. Work includes regressions, survey data cleaning, and contributing to working papers.', category_id: 4, category_name: 'Research', dept_id: 2, dept_name: 'Business Administration', deadline: future(32), opp_mode: 'hybrid', location: 'Lahore / Remote', is_paid: true, stipend: 'PKR 18,000/month', duration: '4 months', required_skills: ['Stata or R', 'Excel', 'Econometrics', 'Academic Writing'], eligibility: 'Any Pakistani university student. Economics or Social Sciences preferred.', application_link: 'https://cer.lums.edu.pk', tags: ['economics', 'development', 'data', 'research'], posted_by: by },
        { title: 'WWF Pakistan — Environmental Data Research Intern', organization: 'WWF Pakistan', description: 'Assist with biodiversity monitoring, deforestation analysis via satellite imagery, and climate vulnerability assessments for northern Pakistan. Tools include QGIS, Python, and field-data management.', category_id: 4, category_name: 'Research', dept_id: 5, dept_name: 'Mathematics', deadline: future(24), opp_mode: 'hybrid', location: 'Islamabad / Field', is_paid: false, stipend: 'Unpaid (stipend under review)', duration: '3 months', required_skills: ['QGIS', 'Python', 'Remote Sensing', 'Data Cleaning'], eligibility: 'Students in Environmental Science, Geography, CS, or Mathematics.', application_link: 'https://www.wwfpak.org/careers', tags: ['environment', 'GIS', 'biodiversity', 'climate'], posted_by: by },
        { title: 'PIDE Research Associate — Pakistan Economy', organization: 'Pakistan Institute of Development Economics', description: 'Work inside PIDE\'s macro-economics and public-policy teams on policy briefs, data collection, and reports submitted to Pakistan\'s Ministry of Finance and the World Bank.', category_id: 4, category_name: 'Research', dept_id: 2, dept_name: 'Business Administration', deadline: future(40), opp_mode: 'on-campus', location: 'Islamabad, Pakistan', is_paid: true, stipend: 'PKR 22,000/month', duration: '6 months', required_skills: ['Economics', 'SPSS or Stata', 'Policy Writing', 'MS Excel'], eligibility: 'BS/MS students or recent graduates in Economics or related fields.', application_link: 'https://pide.org.pk/careers', tags: ['economics', 'policy', 'World-Bank', 'government'], posted_by: by },
    ];

    // ── COURSES (cat 5) ──────────────────────────────────────────────────────
    const courses = [
        { title: 'Devsinc Full-Stack Web Dev Bootcamp', organization: 'Devsinc', description: '8-week intensive MERN-stack bootcamp. Cohorts of 20 build two deployed projects with senior engineer code reviews. Top graduates receive job offers at Devsinc.', category_id: 5, category_name: 'Course', dept_id: 1, dept_name: 'Computer Science', deadline: future(8), opp_mode: 'remote', location: 'Remote', is_paid: false, stipend: 'Free (coding test required)', duration: '8 weeks (4 hrs/day)', required_skills: ['HTML/CSS', 'Basic JavaScript', 'Git'], eligibility: 'CS/SE students or recent graduates. Pass online coding assessment.', application_link: 'https://devsinc.com/bootcamp', tags: ['MERN', 'full-stack', 'bootcamp', 'job-offer'], posted_by: by },
        { title: 'Telenor Academy — Digital Skills Certification', organization: 'Telenor Pakistan', description: 'Free 6-week online certification in Digital Marketing, Data Analytics, Cyber Security, and App Development. 12 hours of video per track + assignments + graded project. Widely recognised by Pakistani employers.', category_id: 5, category_name: 'Course', dept_id: 6, dept_name: 'Psychology', deadline: future(15), opp_mode: 'remote', location: 'Online', is_paid: false, stipend: 'Free certification', duration: '6 weeks (self-paced)', required_skills: [], eligibility: 'All Pakistani university students. CNIC required.', application_link: 'https://telenor.com.pk/telenor-academy', tags: ['digital-skills', 'free', 'certification', 'all-disciplines'], posted_by: by },
        { title: 'Stanford ML Specialisation — Coursera Financial Aid', organization: 'Stanford University / Coursera', description: 'Andrew Ng\'s landmark Machine Learning Specialisation (3 courses). Apply for 100% financial aid with a short essay. Aid typically approved within 15 days. One of the most recognised ML credentials worldwide.', category_id: 5, category_name: 'Course', dept_id: 1, dept_name: 'Computer Science', deadline: future(20), opp_mode: 'remote', location: 'Online (Coursera)', is_paid: false, stipend: 'Free via financial aid', duration: '3 months (self-paced)', required_skills: ['Python Basics', 'Linear Algebra', 'Calculus Basics'], eligibility: 'Anyone with financial need. Submit short essay on Coursera financial aid page.', application_link: 'https://www.coursera.org/specializations/machine-learning-introduction', tags: ['ML', 'Stanford', 'free', 'certificate', 'Python'], posted_by: by },
        { title: 'AWS Cloud Practitioner Scholarship — re:Start', organization: 'Amazon Web Services (AWS)', description: 'Free 12-week full-time cloud programme covering Python, Linux, networking, and cloud fundamentals. Prepares you for the AWS Certified Cloud Practitioner exam (fee covered). Job placement support included.', category_id: 5, category_name: 'Course', dept_id: 1, dept_name: 'Computer Science', deadline: future(30), opp_mode: 'on-campus', location: 'Islamabad / Lahore / Karachi', is_paid: false, stipend: 'Free + AWS exam voucher', duration: '12 weeks (full-time)', required_skills: ['No prior cloud experience needed'], eligibility: 'Any university student or recent graduate. Full-time commitment required.', application_link: 'https://aws.amazon.com/training/restart', tags: ['cloud', 'AWS', 'free', 'certification', 'job-placement'], posted_by: by },
        { title: 'Meta Frontend Developer Professional Certificate', organization: 'Meta / Coursera', description: '9-course programme by Meta engineers covering HTML, CSS, React, UI/UX, and version control. Includes a capstone React project. Financial aid available. Certificate recognised across Pakistan.', category_id: 5, category_name: 'Course', dept_id: 1, dept_name: 'Computer Science', deadline: future(14), opp_mode: 'remote', location: 'Online (Coursera)', is_paid: false, stipend: 'Free via financial aid', duration: '7 months (self-paced)', required_skills: ['Basic Computer Literacy'], eligibility: 'Anyone. Apply for financial aid on Coursera before enrolling.', application_link: 'https://www.coursera.org/professional-certificates/meta-front-end-developer', tags: ['React', 'frontend', 'Meta', 'certificate', 'beginner-friendly'], posted_by: by },
        { title: 'Google UX Design Professional Certificate', organization: 'Google / Coursera', description: 'Learn UX Design from Google\'s own designers through 7 courses covering design thinking, wireframing, Figma prototyping, and usability testing. Financial aid available. No prior design experience needed.', category_id: 5, category_name: 'Course', dept_id: 4, dept_name: 'Media Studies', deadline: future(18), opp_mode: 'remote', location: 'Online (Coursera)', is_paid: false, stipend: 'Free via financial aid', duration: '6 months (self-paced)', required_skills: ['No prior experience needed'], eligibility: 'Open to anyone. Apply for Coursera financial aid.', application_link: 'https://www.coursera.org/professional-certificates/google-ux-design', tags: ['UX', 'Figma', 'design', 'Google', 'certificate'], posted_by: by },
    ];

    // ── EXCHANGE PROGRAMS (cat 6) ────────────────────────────────────────────
    const exchangePrograms = [
        { title: 'Erasmus+ Exchange — TU Munich, Germany', organization: 'TU Munich & Erasmus+', description: 'One semester at TU Munich (top 50 globally for CS/Engineering). Erasmus+ grant covers tuition, EUR 600–800/month, and return flights. Take AI, robotics, or entrepreneurship courses. Credits transfer fully to NUST.', category_id: 6, category_name: 'Exchange Program', dept_id: 1, dept_name: 'Computer Science', deadline: future(65), opp_mode: 'on-campus', location: 'Munich, Germany', is_paid: true, stipend: 'EUR 600–800/month + travel', duration: '1 semester (5 months)', required_skills: ['IELTS 6.0+ or TOEFL 80+'], eligibility: '3rd or 4th year BS. CGPA ≥ 3.0. Nominated by NUST OAA office.', application_link: '', tags: ['Germany', 'Erasmus', 'Europe', 'exchange', 'fully-funded'], posted_by: by },
        { title: 'AIT Thailand Semester Exchange', organization: 'Asian Institute of Technology (AIT)', description: 'Semester exchange in Bangkok at AIT, with students from 50+ countries. NUST waives home tuition while you pay discounted AIT fees. Strong research collaboration with AIT faculty in Engineering.', category_id: 6, category_name: 'Exchange Program', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(55), opp_mode: 'on-campus', location: 'Bangkok, Thailand', is_paid: false, stipend: 'Tuition waiver at NUST', duration: '1 semester', required_skills: ['IELTS 5.5+'], eligibility: 'BS 3rd year+. Good academic standing.', application_link: '', tags: ['Asia', 'Thailand', 'exchange', 'engineering'], posted_by: by },
        { title: 'South Korea POSTECH Exchange Program', organization: 'POSTECH (Pohang University of Science & Technology)', description: 'One-semester exchange at POSTECH, ranked Asia\'s top 10 for science and technology. Study advanced AI, semiconductor engineering, or bioinformatics. Dormitory accommodation provided on campus.', category_id: 6, category_name: 'Exchange Program', dept_id: 1, dept_name: 'Computer Science', deadline: future(70), opp_mode: 'on-campus', location: 'Pohang, South Korea', is_paid: false, stipend: 'Dorm provided (tuition waiver at NUST)', duration: '1 semester', required_skills: ['English Proficiency', 'Strong Academic Standing'], eligibility: 'BS 3rd year+ in CS or EE. Apply through NUST OAA.', application_link: '', tags: ['South-Korea', 'Asia', 'POSTECH', 'engineering'], posted_by: by },
        { title: 'Japan JASSO Short-Term Exchange — Kyoto University', organization: 'Japan Student Services Organisation (JASSO)', description: 'Study at Kyoto University for one semester with a JPY 80,000/month JASSO stipend. One of Japan\'s most prestigious institutions with world-class CS, robotics, and physics programs.', category_id: 6, category_name: 'Exchange Program', dept_id: 1, dept_name: 'Computer Science', deadline: future(58), opp_mode: 'on-campus', location: 'Kyoto, Japan', is_paid: true, stipend: 'JPY 80,000/month from JASSO', duration: '1 semester', required_skills: ['TOEFL 72+ or IELTS 5.5+'], eligibility: 'BS 3rd year+ in CS/EE/Sciences. CGPA ≥ 3.2.', application_link: '', tags: ['Japan', 'JASSO', 'Kyoto', 'stipend', 'exchange'], posted_by: by },
        { title: 'China Scholarship Council (CSC) — Full Scholarship', organization: 'China Scholarship Council / Chinese Universities', description: 'Full scholarship for Pakistani students at top Chinese universities (Tsinghua, Peking, Fudan, USTC). Covers tuition, accommodation, health insurance, and monthly stipend. Available for BS, Master\'s, and PhD.', category_id: 6, category_name: 'Exchange Program', dept_id: 1, dept_name: 'Computer Science', deadline: future(48), opp_mode: 'on-campus', location: 'Beijing / Shanghai / Hefei, China', is_paid: true, stipend: 'CNY 2,500–3,500/month + tuition + dorm', duration: '4 yrs (BS) / 2–3 yrs (Master\'s) / 3–4 yrs (PhD)', required_skills: ['Academic Excellence'], eligibility: 'Pakistani citizens under 35. CGPA ≥ 3.0. Apply through HEC.', application_link: 'https://www.hec.gov.pk/csc', tags: ['China', 'fully-funded', 'Tsinghua', 'BS', 'masters', 'PhD'], posted_by: by },
        { title: 'Turkey Mevlana Exchange Programme', organization: 'Council of Higher Education Turkey (YÖK)', description: 'Study for one or two semesters at METU, ITU, or Bogazici University. Turkey\'s top universities have excellent engineering and social science departments. Full credit transfer to NUST recognised.', category_id: 6, category_name: 'Exchange Program', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(44), opp_mode: 'on-campus', location: 'Ankara / Istanbul, Turkey', is_paid: false, stipend: 'Tuition waiver at NUST', duration: '1–2 semesters', required_skills: ['IELTS 5.5+'], eligibility: 'BS 2nd year+ in any discipline. CGPA ≥ 2.5.', application_link: '', tags: ['Turkey', 'METU', 'Bogazici', 'Europe', 'exchange'], posted_by: by },
    ];

    // ── COMPETITIONS (cat 7) ─────────────────────────────────────────────────
    const competitions = [
        { title: 'ICPC Asia Regionals 2025 — Lahore Site', organization: 'ACM-ICPC', description: 'Teams of 3 solve algorithmic problems in 5 hours at the ACM-ICPC Asia Regionals. Top teams qualify for ICPC World Finals. NUST ACM Chapter provides practice sessions and travel grants.', category_id: 7, category_name: 'Competition', dept_id: 1, dept_name: 'Computer Science', deadline: future(7), opp_mode: 'on-campus', location: 'UET Lahore', is_paid: false, stipend: 'Travel grant for top 3 NUST teams', duration: '1-day competition', required_skills: ['Competitive Programming', 'Algorithms', 'C++ or Java'], eligibility: 'Full-time students. Teams of exactly 3.', application_link: '', tags: ['competitive-programming', 'algorithms', 'ICPC', 'world-finals'], posted_by: by },
        { title: 'Microsoft Imagine Cup 2025', organization: 'Microsoft', description: 'World\'s premier student technology competition. Build a tech solution addressing a global challenge. National → Regional → World Finals (USD 100,000 prize). Top Pakistani teams have won global rounds.', category_id: 7, category_name: 'Competition', dept_id: 1, dept_name: 'Computer Science', deadline: future(40), opp_mode: 'remote', location: 'Online → World Finals (Seattle)', is_paid: true, stipend: 'USD 100,000 (World Finals winner)', duration: '3 months (qualifying) + Finals', required_skills: ['Azure', 'AI/ML', 'Pitching', 'Any Tech Stack'], eligibility: 'Enrolled students aged 18+. Teams of 1–3.', application_link: 'https://imaginecup.microsoft.com', tags: ['global', 'Azure', 'AI', 'prize', 'impact'], posted_by: by },
        { title: 'NUST Incubator Business Plan Competition', organization: 'NUST Technology Incubator (NIC)', description: 'Annual competition where NUST teams pitch startup ideas to VCs and industry experts. Top 10 teams get free co-working space. Winner receives PKR 2,000,000 seed funding from NIC.', category_id: 7, category_name: 'Competition', dept_id: 2, dept_name: 'Business Administration', deadline: future(25), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: true, stipend: 'PKR 2,000,000 seed funding (winner)', duration: '2-day final', required_skills: ['Business Planning', 'Financial Modeling', 'Pitching'], eligibility: 'NUST students only. Teams of 2–5.', application_link: '', tags: ['startup', 'seed-funding', 'entrepreneurship', 'NIC'], posted_by: by },
        { title: 'CFA Institute Research Challenge — Pakistan', organization: 'CFA Society Pakistan', description: 'University teams produce a professional equity research report on an assigned Pakistani listed company and present to CFA Charterholders. Winning team represents Pakistan at the global CFA Research Challenge.', category_id: 7, category_name: 'Competition', dept_id: 2, dept_name: 'Business Administration', deadline: future(33), opp_mode: 'on-campus', location: 'Karachi / Islamabad', is_paid: false, stipend: 'Global winner: prestige + CFA resources', duration: '3 months (research) + 1-day final', required_skills: ['Financial Modelling', 'DCF Valuation', 'Report Writing', 'Excel'], eligibility: 'University students in Finance, Economics, or Business. Teams of 3–5.', application_link: 'https://cfasociety.org.pk/research-challenge', tags: ['finance', 'equity-research', 'CFA', 'global'], posted_by: by },
        { title: 'Ericsson Innovation Awards', organization: 'Ericsson', description: 'Ericsson\'s global competition challenges teams to develop innovative 5G and IoT solutions. Pakistani teams have placed in the global top 20. Finalists present to Ericsson leadership in Stockholm.', category_id: 7, category_name: 'Competition', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(28), opp_mode: 'remote', location: 'Online → Global Finals (Stockholm)', is_paid: true, stipend: 'EUR 10,000 (Global winner)', duration: '6 months', required_skills: ['5G', 'IoT', 'Innovation', 'Prototype Development'], eligibility: 'University students worldwide. Teams of 3–5.', application_link: 'https://www.ericsson.com/en/careers/university/innovation-awards', tags: ['5G', 'IoT', 'Ericsson', 'global', 'telecom'], posted_by: by },
        { title: 'P&G CEO Challenge', organization: 'Procter & Gamble Pakistan', description: 'Teams solve a real P&G brand problem in Pakistan. Online submission → finals at P&G HQ. Winners receive PKR 100,000 + fast-track interview for internship at P&G.', category_id: 7, category_name: 'Competition', dept_id: 2, dept_name: 'Business Administration', deadline: future(15), opp_mode: 'hybrid', location: 'Karachi (Finals)', is_paid: true, stipend: 'PKR 100,000 (winners) + internship fast-track', duration: '4 weeks', required_skills: ['Case Analysis', 'Strategy', 'Presentation', 'Teamwork'], eligibility: 'Penultimate or final year students. Any discipline. Teams of 4.', application_link: 'https://www.pg.com.pk/careers', tags: ['FMCG', 'business-case', 'strategy', 'P&G', 'internship'], posted_by: by },
    ];

    // ── WORKSHOPS (cat 8) ────────────────────────────────────────────────────
    const workshops = [
        { title: 'GDSC NUST — Google Technologies Workshop Series', organization: 'Google Developer Student Clubs', description: 'Semester-long workshop series covering Flutter, Firebase, Google Cloud, and TensorFlow Lite. Each session is 3 hours with hands-on labs. Attendees build and deploy a real project by the end.', category_id: 8, category_name: 'Workshop', dept_id: 1, dept_name: 'Computer Science', deadline: future(5), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: false, stipend: 'Free', duration: '8 sessions (1 per week)', required_skills: ['Basic Programming'], eligibility: 'Open to all NUST students.', application_link: '', tags: ['Google', 'Flutter', 'Firebase', 'cloud', 'free'], posted_by: by },
        { title: 'AWS Cloud Fundamentals Technical Workshop', organization: 'Amazon Web Services (AWS)', description: 'One-day intensive workshop by AWS Solutions Architects covering EC2, S3, Lambda, and RDS. Attendees get USD 50 AWS credits for live labs. AWS certificate of attendance issued.', category_id: 8, category_name: 'Workshop', dept_id: 1, dept_name: 'Computer Science', deadline: future(10), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: false, stipend: 'Free + USD 50 AWS credits', duration: '1 day (8 hours)', required_skills: ['Basic Linux', 'Networking Concepts'], eligibility: 'Any university student. Bring a laptop.', application_link: 'https://aws.amazon.com/training/events', tags: ['AWS', 'cloud', 'labs', 'free', 'certificate'], posted_by: by },
        { title: 'IEEE Pakistan — Robotics & Embedded Systems Workshop', organization: 'IEEE Pakistan Section', description: 'Two-day hands-on workshop on Arduino robotics and ROS. Participants build a line-following robot and a robotic arm controller. Components provided on-site. IEEE membership not required.', category_id: 8, category_name: 'Workshop', dept_id: 3, dept_name: 'Electrical Engineering', deadline: future(7), opp_mode: 'on-campus', location: 'NUST SEECS, Islamabad', is_paid: false, stipend: 'Free (limited to 40 seats)', duration: '2 days (16 hours total)', required_skills: ['Basic Electronics', 'C Programming'], eligibility: 'EE, Mechatronics, or CS students. 2nd year and above.', application_link: '', tags: ['robotics', 'Arduino', 'ROS', 'IEEE', 'embedded'], posted_by: by },
        { title: 'UN Youth Forum — SDGs & Leadership Workshop', organization: 'United Nations Pakistan / UNDP', description: 'Full-day UN-facilitated workshop on the Sustainable Development Goals, advocacy skills, and youth leadership. Participants develop campus action plans. UNDP Pakistan certificate of attendance issued.', category_id: 8, category_name: 'Workshop', dept_id: 6, dept_name: 'Psychology', deadline: future(12), opp_mode: 'on-campus', location: 'Islamabad', is_paid: false, stipend: 'Free', duration: '1 day (8 hours)', required_skills: ['Public Speaking', 'Leadership Interest'], eligibility: 'All Pakistani university students. Limited to 60 seats.', application_link: 'https://www.pk.undp.org/youth', tags: ['UN', 'SDGs', 'leadership', 'advocacy', 'certificate'], posted_by: by },
        { title: 'Startup Weekend NUST — 54-Hour Startup Bootcamp', organization: 'Techstars / NUST Entrepreneurship Centre', description: 'Pitch an idea Friday night, form a team, validate with real customers, and demo an MVP on Sunday. Coaches from Google, Careem, and Systems Limited mentor teams throughout the event.', category_id: 8, category_name: 'Workshop', dept_id: 2, dept_name: 'Business Administration', deadline: future(6), opp_mode: 'on-campus', location: 'NUST, Islamabad', is_paid: false, stipend: 'PKR 500 registration fee only', duration: '54 hours (Fri evening – Sun evening)', required_skills: ['Entrepreneurial Mindset', 'Any Skill (Design / Code / Business)'], eligibility: 'Open to all university students and recent graduates.', application_link: 'https://startupweekend.org', tags: ['startup', 'entrepreneurship', 'MVP', 'Techstars', 'Careem'], posted_by: by },
        { title: 'Accenture Future Talent — Digital Skills Workshop', organization: 'Accenture Pakistan', description: 'Half-day workshop on Agile project management, data-driven decision making, and digital transformation strategy — run by Accenture Managing Directors. Complete a mini case study and earn a LinkedIn digital badge. Fast-tracks into Accenture campus hiring.', category_id: 8, category_name: 'Workshop', dept_id: 2, dept_name: 'Business Administration', deadline: future(13), opp_mode: 'on-campus', location: 'Karachi / Islamabad', is_paid: false, stipend: 'Free (LinkedIn digital badge)', duration: '4 hours', required_skills: ['Business Basics', 'Communication'], eligibility: 'Penultimate and final year students. All disciplines.', application_link: 'https://www.accenture.com/pk-en/careers/students', tags: ['Accenture', 'Agile', 'digital', 'LinkedIn-badge', 'hiring'], posted_by: by },
    ];

    const all = await Opportunity.insertMany([
        ...internships, ...scholarships, ...hackathons,
        ...research, ...courses, ...exchangePrograms,
        ...competitions, ...workshops,
    ]);
    console.log(`✔ Inserted ${all.length} opportunities`);

    const notifs = all.map(o => ({
        user_id: student._id, opp_id: o._id,
        message: `New opportunity posted: ${o.title}`, is_read: false,
    }));
    await Notification.insertMany(notifs);
    console.log(`✔ Inserted ${notifs.length} notifications for demo_student`);

    const tally = {};
    all.forEach(o => { tally[o.category_name] = (tally[o.category_name] || 0) + 1; });
    console.log('\n📊 Count per category:');
    Object.entries(tally).forEach(([cat, n]) => console.log(`   ${cat.padEnd(22)} ${n}`));

    console.log('\n✅ Seed complete!');
    console.log('   Admin   → admin@campus.edu      / admin123');
    console.log('   Student → student@seecs.edu.pk  / student123');
    await mongoose.disconnect();
}

seed().catch(err => { console.error('Seed failed:', err); process.exit(1); });
