require('dotenv').config({ path: require('path').resolve(__dirname, '../backend/.env') });
const mongoose = require('mongoose');
const bcrypt   = require('bcrypt');

const User             = require('../backend/models/User');
const Opportunity      = require('../backend/models/Opportunity');
const SavedOpportunity = require('../backend/models/SavedOpportunity');
const Notification     = require('../backend/models/Notification');

// Days-from-now helper — always future regardless of when you re-run the seed
const d = (days) => new Date(Date.now() + days * 86_400_000);

async function seed() {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✔ Connected to MongoDB');

    await Promise.all([
        User.deleteMany({}), Opportunity.deleteMany({}),
        SavedOpportunity.deleteMany({}), Notification.deleteMany({}),
    ]);
    console.log('✔ Cleared existing data');

    // ── Users ────────────────────────────────────────────────────────────────
    const [admin, student] = await User.insertMany([
        { user_name: 'admin',        email: 'admin@campus.edu',     password_hash: await bcrypt.hash('admin123',   10), role_id: 1, dept_id: 1, dept_name: 'Computer Science', is_verified: true },
        { user_name: 'demo_student', email: 'student@seecs.edu.pk', password_hash: await bcrypt.hash('student123', 10), role_id: 2, dept_id: 1, dept_name: 'Computer Science', is_verified: true },
    ]);
    const by = admin._id;
    console.log('✔ Created users');

    // =========================================================================
    //  CATEGORY 1 — INTERNSHIPS
    // =========================================================================
    const internships = [
        {
            title: 'Google Summer of Code 2025',
            organization: 'Google',
            description: 'GSoC connects university students with open-source organisations for a 3-month paid coding project. Students are mentored by experienced engineers, contribute to widely-used software, and build a strong public GitHub portfolio. Acceptance rate ~15% globally.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(60), opp_mode: 'remote', location: 'Remote (Global)',
            is_paid: true, stipend: 'USD 3,000 – 6,600 (lump sum)',
            duration: '3 months (May – Aug)',
            required_skills: ['Git', 'Open Source contributions', 'Python / C++ / JavaScript'],
            eligibility: 'Enrolled university students aged 18+. At least one open-source contribution.',
            application_link: 'https://summerofcode.withgoogle.com',
            tags: ['open-source', 'coding', 'mentorship', 'remote'], posted_by: by,
        },
        {
            title: 'Microsoft Explore Internship 2026',
            organization: 'Microsoft',
            description: 'A 12-week internship for freshmen and sophomores exploring software engineering and program management. Interns ship real features in Microsoft 365, Azure, or Teams, attend senior-leader Q&As, and complete a team design challenge with real user impact.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(90), opp_mode: 'hybrid', location: 'Redmond, WA (Hybrid)',
            is_paid: true, stipend: 'USD 7,000/month + relocation allowance',
            duration: '12 weeks (June – Aug)',
            required_skills: ['C#', '.NET', 'Azure', 'Data Structures', 'Algorithms'],
            eligibility: 'Freshman or sophomore in CS/related field. CGPA ≥ 3.2.',
            application_link: 'https://careers.microsoft.com',
            tags: ['cloud', 'product', 'global', 'USA'], posted_by: by,
        },
        {
            title: 'Meta Software Engineering Internship',
            organization: 'Meta (Facebook)',
            description: 'Work on the infrastructure powering 3 billion users across Facebook, Instagram, and WhatsApp. Interns are embedded in a real product team, attend technical mentorship sessions, and present their project at an end-of-summer intern showcase.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(75), opp_mode: 'hybrid', location: 'Menlo Park, CA / Remote',
            is_paid: true, stipend: 'USD 8,500/month + housing stipend',
            duration: '12 weeks (May – Aug)',
            required_skills: ['C++', 'Python', 'Data Structures', 'System Design'],
            eligibility: 'BS/MS students in CS/CE. Penultimate or final year preferred.',
            application_link: 'https://www.metacareers.com/students',
            tags: ['social-media', 'infrastructure', 'global', 'USA'], posted_by: by,
        },
        {
            title: 'Amazon SDE Internship (AWS)',
            organization: 'Amazon Web Services',
            description: 'Build, scale, and operate AWS services used by millions of developers worldwide. Interns own a feature end-to-end — design doc, implementation, code review, and production deployment. Mentored by senior SDEs, with structured 1:1 feedback every two weeks.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(95), opp_mode: 'hybrid', location: 'Seattle, WA / Dublin',
            is_paid: true, stipend: 'USD 8,000/month + relocation',
            duration: '12 weeks',
            required_skills: ['Java', 'Python', 'Distributed Systems', 'OOP', 'Algorithms'],
            eligibility: 'CS/CE students. Penultimate or final year. LeetCode medium proficiency.',
            application_link: 'https://amazon.jobs/students',
            tags: ['cloud', 'AWS', 'distributed-systems', 'SDE'], posted_by: by,
        },
        {
            title: 'Systems Limited Graduate Internship',
            organization: 'Systems Limited',
            description: "Pakistan's largest IT exporter embeds interns directly in product teams building fintech, ERP, and digital-transformation solutions for global clients. Structured 3-month programme with mentorship, tech talks, and a pre-placement offer for top performers.",
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(45), opp_mode: 'on-campus', location: 'Lahore, Pakistan',
            is_paid: true, stipend: 'PKR 40,000/month',
            duration: '3 months',
            required_skills: ['Java', 'Spring Boot', 'SQL', 'REST APIs'],
            eligibility: 'Final-year or recently graduated BS CS/SE/IT. CGPA ≥ 3.0.',
            application_link: 'https://www.systemsltd.com/careers',
            tags: ['fintech', 'enterprise', 'pre-placement', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Careem Product & Engineering Internship',
            organization: 'Careem (Uber Company)',
            description: 'Join the super-app trusted by 50 million users across the Middle East and South Asia. Engineering interns are embedded in squads building ride-hailing, food delivery, or fintech features in a true microservices architecture. Demo your project to VP Engineering.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(80), opp_mode: 'hybrid', location: 'Karachi / Remote',
            is_paid: true, stipend: 'PKR 65,000/month',
            duration: '3 months',
            required_skills: ['Kotlin', 'Node.js', 'Microservices', 'AWS'],
            eligibility: 'Penultimate or final year CS/SE. Mobile or backend experience required.',
            application_link: 'https://careem.com/careers',
            tags: ['super-app', 'mobile', 'backend', 'MENA', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Arbisoft Summer Internship 2026',
            organization: 'Arbisoft',
            description: "Work on US-based client SaaS products with senior engineers at one of Pakistan's fastest-growing software companies. Bi-weekly learning sessions, code-quality workshops, and a demo day. Strong performers receive return full-time offers.",
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(120), opp_mode: 'hybrid', location: 'Lahore, Pakistan',
            is_paid: true, stipend: 'PKR 35,000/month',
            duration: '2 months (June – July)',
            required_skills: ['React', 'Django', 'Python', 'PostgreSQL'],
            eligibility: '3rd or 4th year CS/SE. Must have completed at least one web project.',
            application_link: 'https://arbisoft.com/careers',
            tags: ['web-development', 'startup', 'SaaS', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Jazz Digital & AI Innovation Internship',
            organization: 'Jazz (Veon Group)',
            description: "Pakistan's largest telecom recruits CS/EE interns for its Digital & AI division. Work on predictive churn models, network analytics dashboards, and AI-driven customer care. Exposure to petabyte-scale real-time data pipelines built on Kafka and Spark.",
            category_id: 1, category_name: 'Internship',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(55), opp_mode: 'on-campus', location: 'Islamabad, Pakistan',
            is_paid: true, stipend: 'PKR 45,000/month',
            duration: '6 weeks',
            required_skills: ['Python', 'SQL', 'Machine Learning', 'Data Analytics'],
            eligibility: '3rd/4th year EE, CS, or DS students. Data analysis experience preferred.',
            application_link: 'https://jazz.com.pk/careers',
            tags: ['telecom', 'AI', 'data', 'Pakistan', 'Spark'], posted_by: by,
        },
        {
            title: 'NetSol Technologies Internship',
            organization: 'NetSol Technologies',
            description: 'NetSol is a NASDAQ-listed Pakistani software company serving global automotive and leasing clients. Interns join real product teams building enterprise software used in 100+ countries. The structured programme includes weekly tech talks and a final presentation.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(100), opp_mode: 'on-campus', location: 'Lahore, Pakistan',
            is_paid: true, stipend: 'PKR 30,000/month',
            duration: '3 months',
            required_skills: ['.NET', 'SQL Server', 'JavaScript', 'OOP'],
            eligibility: '3rd or 4th year CS/SE. CGPA ≥ 2.8.',
            application_link: 'https://www.netsoltech.com/careers',
            tags: ['NASDAQ', 'enterprise', 'automotive-software', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Bytedance (TikTok) SWE Intern — Singapore',
            organization: 'ByteDance / TikTok',
            description: 'ByteDance Singapore office hires BS/MS SWE interns for backend, ML, and mobile teams. Work on systems serving 1 billion+ users. International travel and accommodation support provided. Very competitive but high-impact for resume.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(110), opp_mode: 'on-campus', location: 'Singapore',
            is_paid: true, stipend: 'SGD 4,500/month',
            duration: '3 months',
            required_skills: ['Go', 'C++', 'Java', 'System Design', 'Data Structures'],
            eligibility: 'BS/MS CS students. Penultimate or final year. Strong DSA required.',
            application_link: 'https://jobs.bytedance.com/campus',
            tags: ['TikTok', 'Singapore', 'backend', 'ML', 'global'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 2 — SCHOLARSHIPS
    // =========================================================================
    const scholarships = [
        {
            title: 'HEC Need-Based Scholarship 2025–26',
            organization: 'Higher Education Commission Pakistan',
            description: 'Financial assistance for deserving students enrolled in recognised HEIs. Covers tuition fees, hostel charges, and a monthly stipend for up to 4 years. One of the largest government scholarship programmes in Pakistan.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(180), opp_mode: 'on-campus', location: 'Pakistan (All HEIs)',
            is_paid: true, stipend: 'PKR 60,000/year + tuition waiver',
            duration: 'Up to 4 years (renewable annually)',
            required_skills: [],
            eligibility: 'Pakistani BS students. Family income < PKR 45,000/month. CGPA ≥ 2.5.',
            application_link: 'https://www.hec.gov.pk/needbased',
            tags: ['need-based', 'undergraduate', 'government', 'HEC'], posted_by: by,
        },
        {
            title: 'DAAD Scholarship — Study in Germany 2026',
            organization: 'DAAD (German Academic Exchange Service)',
            description: "Full scholarship for outstanding Pakistani students pursuing Master's or PhD at top German universities. Covers tuition, EUR 934/month living allowance, health insurance, travel grant, and German language courses before departure.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(75), opp_mode: 'on-campus', location: 'Germany',
            is_paid: true, stipend: 'EUR 934/month + tuition + airfare',
            duration: "1–2 years (Master's) / 3 years (PhD)",
            required_skills: ['Academic Excellence', 'Research Proposal', 'English/German Proficiency'],
            eligibility: "BS graduates CGPA ≥ 3.0. Max age 32 (Master's) / 35 (PhD).",
            application_link: 'https://www.daad.de/en',
            tags: ['Germany', 'masters', 'PhD', 'fully-funded', 'Europe'], posted_by: by,
        },
        {
            title: 'Commonwealth Scholarship — United Kingdom',
            organization: 'Commonwealth Scholarship Commission',
            description: "Fully funded scholarships for Commonwealth citizens to pursue Master's and PhD degrees at UK universities. Includes tuition, GBP 1,236/month living allowance, return airfare, warm clothing allowance, and thesis grant.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(90), opp_mode: 'on-campus', location: 'United Kingdom',
            is_paid: true, stipend: 'GBP 1,236/month + tuition + airfare',
            duration: "1 year (Master's) / 3 years (PhD)",
            required_skills: ['First/Upper-Second Class Degree', 'IELTS 6.5+'],
            eligibility: "Pakistani citizens. Upper-second or first class Bachelor's.",
            application_link: 'https://www.hec.gov.pk/commonwealth',
            tags: ['UK', 'fully-funded', 'development', 'masters', 'Commonwealth'], posted_by: by,
        },
        {
            title: 'Chevening Scholarship — UK Government 2026',
            organization: 'UK Foreign, Commonwealth & Development Office',
            description: "The UK government's flagship international scholarship. Fully funded for a 1-year Master's at any UK university. Covers tuition, living costs (GBP 1,200/month in London), flights, and the Chevening community — over 50,000 global alumni.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(30), opp_mode: 'on-campus', location: 'United Kingdom',
            is_paid: true, stipend: 'Full tuition + GBP 1,200/month + airfare',
            duration: "1 year Master's",
            required_skills: ['Leadership Experience', 'IELTS 6.5+', 'Work Experience (2 years)'],
            eligibility: 'Pakistani citizens under 35. Min 2 years work/leadership experience.',
            application_link: 'https://www.chevening.org/apply',
            tags: ['UK', 'Chevening', 'leadership', 'fully-funded', 'government'], posted_by: by,
        },
        {
            title: 'Fulbright Scholarship — USA (Master\'s & PhD)',
            organization: 'US Embassy Islamabad / Fulbright',
            description: "The prestigious Fulbright Program funds Pakistani students to pursue Master's and PhD degrees at US universities. Covers full tuition, monthly stipend, health insurance, and round-trip airfare. One of the most competitive scholarships in Pakistan.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(210), opp_mode: 'on-campus', location: 'United States',
            is_paid: true, stipend: 'Full tuition + USD 1,500–2,000/month + health',
            duration: "2 years (Master's) / 4–5 years (PhD)",
            required_skills: ['GRE 310+', 'TOEFL 90+', 'Academic Excellence', 'Statement of Purpose'],
            eligibility: 'Pakistani citizens. BS degree. Under 40 for Master\'s; no age limit for PhD.',
            application_link: 'https://www.usefpakistan.org',
            tags: ['USA', 'Fulbright', 'fully-funded', 'masters', 'PhD'], posted_by: by,
        },
        {
            title: 'Aga Khan Foundation International Scholarship',
            organization: 'Aga Khan Foundation',
            description: "Postgraduate scholarships for outstanding students from developing countries. Structured as 50% grant + 50% interest-free loan for Master's and PhD programmes worldwide. Focuses on students with no other funding source.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(140), opp_mode: 'on-campus', location: 'International',
            is_paid: true, stipend: '50% grant + 50% interest-free loan',
            duration: 'Duration of postgraduate programme',
            required_skills: ['Academic Excellence', 'Community Service Record'],
            eligibility: 'Pakistani citizens. Outstanding merit and demonstrated financial need.',
            application_link: 'https://www.akdn.org/AKF_Scholarships',
            tags: ['postgraduate', 'merit-need', 'international', 'AKF'], posted_by: by,
        },
        {
            title: 'Teach For Pakistan Fellowship',
            organization: 'Teach For Pakistan',
            description: 'Two-year paid fellowship placing talented graduates as full-time teachers in under-resourced schools in Karachi, Lahore, and Islamabad. Includes intensive 5-week training, ongoing coaching, and leadership development. Alumni go on to policy, NGO, and tech roles.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(160), opp_mode: 'on-campus', location: 'Karachi / Lahore / Islamabad',
            is_paid: true, stipend: 'PKR 45,000/month',
            duration: '2 years',
            required_skills: ['Communication', 'Leadership', 'Resilience'],
            eligibility: 'Graduates (within 3 years of graduation). Any discipline. CGPA ≥ 3.0.',
            application_link: 'https://teachforpakistan.org/fellowship',
            tags: ['fellowship', 'education', 'social-impact', 'leadership', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Australian Awards Scholarship (Pakistan)',
            organization: 'Australian Government (DFAT)',
            description: "Fully funded scholarship by the Australian government for Pakistani students to pursue undergraduate or postgraduate studies at Australian universities. Includes tuition, living allowance (AUD 26,000/year), airfare, OSHC health cover, and pre-course English.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(115), opp_mode: 'on-campus', location: 'Australia',
            is_paid: true, stipend: 'AUD 26,000/year + tuition + airfare',
            duration: '2–4 years',
            required_skills: ['IELTS 6.5+', 'Academic Excellence'],
            eligibility: 'Pakistani citizens aged 18+. Min 2 years work experience preferred.',
            application_link: 'https://www.australianawards.gov.au',
            tags: ['Australia', 'fully-funded', 'government', 'masters', 'development'], posted_by: by,
        },
        {
            title: 'HEC Indigenous PhD Scholarship',
            organization: 'Higher Education Commission Pakistan',
            description: "HEC's flagship PhD scholarship for Pakistani students to pursue doctoral research at top local universities (NUST, LUMS, QAU, UET). Covers tuition, research grant (PKR 500,000/year), and a monthly stipend for the full PhD duration.",
            category_id: 2, category_name: 'Scholarship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(155), opp_mode: 'on-campus', location: 'Pakistan',
            is_paid: true, stipend: 'PKR 45,000/month + research grant',
            duration: '3–5 years',
            required_skills: ['Research Proposal', 'MS degree', 'CGPA ≥ 3.0'],
            eligibility: 'Pakistani citizens with an MS degree. CGPA ≥ 3.0.',
            application_link: 'https://www.hec.gov.pk/indigenous-phd',
            tags: ['PhD', 'indigenous', 'HEC', 'government', 'research'], posted_by: by,
        },
        {
            title: 'Atlas Corps Global Leadership Fellowship (USA)',
            organization: 'Atlas Corps (Washington DC)',
            description: 'Atlas Corps places skilled emerging leaders at US-based nonprofits for 12–18 month paid fellowships. Past Pakistani fellows served at Amnesty International, CARE, and Brookings. Includes health insurance and access to a 1,000+ strong global alumni network.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(125), opp_mode: 'on-campus', location: 'Washington DC, USA',
            is_paid: true, stipend: 'USD 1,500/month + health insurance',
            duration: '12–18 months',
            required_skills: ['Leadership', 'English Proficiency', 'Community Work'],
            eligibility: 'Graduates aged 21–35. Min 2 years experience in social sector.',
            application_link: 'https://atlascorps.org/apply',
            tags: ['fellowship', 'USA', 'nonprofit', 'leadership', 'fully-funded'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 3 — HACKATHONS
    // =========================================================================
    const hackathons = [
        {
            title: 'NUST AI Hackathon — Build the Future 2026',
            organization: 'NUST Centre for Artificial Intelligence',
            description: '48-hour AI hackathon on campus with tracks in Healthcare, Climate, Education, and FinTech. Teams of 2–4 build an AI-powered prototype. Winners receive a seed grant, incubator access, and pitch to a panel of VCs. Meals and accommodation provided on-site.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(185), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'Prize Pool: PKR 500,000',
            duration: '48 hours',
            required_skills: ['Python', 'Machine Learning', 'TensorFlow / PyTorch'],
            eligibility: 'All enrolled NUST students. Teams of 2–4.',
            application_link: '',
            tags: ['AI', 'machine-learning', '48-hour', 'prize', 'NUST'], posted_by: by,
        },
        {
            title: 'HackNUST 2026 — Inter-University Hackathon',
            organization: 'NUST ACM Student Chapter',
            description: 'Annual inter-university 36-hour hackathon hosted by NUST ACM. Teams from across Pakistan compete in Fintech, Smart Cities, EdTech, and Health tracks. Mentors from Careem, Telenor, and NUST faculty support teams throughout the event.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(200), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 150,000 total prizes',
            duration: '36 hours',
            required_skills: ['Any Tech Stack', 'Rapid Prototyping', 'Teamwork'],
            eligibility: 'Open to all Pakistani university students. Teams of 3–5.',
            application_link: '',
            tags: ['inter-university', 'fintech', 'EdTech', 'NUST', 'ACM'], posted_by: by,
        },
        {
            title: 'NASA Space Apps Challenge — Pakistan 2026',
            organization: 'NASA / SUPARCO',
            description: "The world's largest annual hackathon co-organised by NASA and SUPARCO. Teams solve real space and Earth science challenges using NASA's open datasets. Local winners advance to NASA's global judging. No aerospace background required — engineers, designers, storytellers welcome.",
            category_id: 3, category_name: 'Hackathon',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(105), opp_mode: 'on-campus', location: 'Islamabad / Lahore / Karachi',
            is_paid: false, stipend: 'Global winner: NASA facility visit',
            duration: '2 days (48 hours)',
            required_skills: ['Data Visualisation', 'Python or JavaScript', 'Creative Problem Solving'],
            eligibility: 'Any university student. Teams of 1–6. Any discipline welcome.',
            application_link: 'https://www.spaceappschallenge.org',
            tags: ['NASA', 'space', 'data', 'global', 'open-data'], posted_by: by,
        },
        {
            title: 'GitHub Copilot AI Hackathon',
            organization: 'GitHub (Microsoft)',
            description: 'Build any project using GitHub Copilot and submit your repository. Judged on code quality, innovation, and real-world impact. Rolling monthly submissions — great for building an open-source portfolio visible to employers worldwide.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(35), opp_mode: 'remote', location: 'Remote (Global)',
            is_paid: true, stipend: 'USD 5,000 monthly prize',
            duration: 'Rolling monthly submissions',
            required_skills: ['Any Programming Language', 'GitHub', 'GitHub Copilot'],
            eligibility: 'Any developer worldwide. Individual or team (max 4).',
            application_link: 'https://github.com/hackathon',
            tags: ['AI', 'GitHub', 'open-source', 'remote', 'Copilot'], posted_by: by,
        },
        {
            title: 'Telenor Digital Innovation Challenge 2026',
            organization: 'Telenor Pakistan',
            description: 'Annual innovation challenge for university teams to pitch digital solutions for connectivity and digital inclusion in Pakistan. Online qualifying → top 10 teams fly to Islamabad finals. Winner receives PKR 300,000 + internship offer at Telenor.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(145), opp_mode: 'hybrid', location: 'Islamabad (Final) / Online',
            is_paid: true, stipend: 'PKR 300,000 + internship offer',
            duration: '3 weeks online + 2-day final',
            required_skills: ['Product Design', 'Business Modelling', 'Prototyping'],
            eligibility: 'University students from any discipline. Teams of 3.',
            application_link: 'https://telenor.com.pk/innovation-challenge',
            tags: ['telecom', 'innovation', 'startup', 'prize', 'Pakistan'], posted_by: by,
        },
        {
            title: 'i.Code — NUST Programming Contest',
            organization: 'NUST SEECS Computing Society',
            description: 'Monthly online coding contest open to all NUST students. Problems span 3 difficulty levels. Top performers earn certificates, NUST ACM points, and priority registration for HackNUST. Great preparation for ICPC regionals.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(150), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'Certificates + ACM points',
            duration: '3 hours (monthly)',
            required_skills: ['C++', 'Data Structures', 'Algorithms'],
            eligibility: 'All NUST CS/SE/EE students.',
            application_link: '',
            tags: ['competitive-programming', 'algorithms', 'NUST', 'monthly'], posted_by: by,
        },
        {
            title: 'Meta Open Source Hackathon',
            organization: 'Meta (Facebook)',
            description: "Meta's global hackathon for students to build projects using React, PyTorch, LLAMA, or Llama Index. Submissions are evaluated by Meta engineers. Top projects are featured on Meta's open-source blog and developers receive Meta swag + gift cards.",
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(120), opp_mode: 'remote', location: 'Remote (Global)',
            is_paid: true, stipend: 'USD 2,000 gift cards + Meta swag',
            duration: '4 weeks (rolling submissions)',
            required_skills: ['React', 'PyTorch', 'LLMs', 'Open Source'],
            eligibility: 'University students worldwide. Individual or team (max 3).',
            application_link: 'https://developers.facebook.com/community',
            tags: ['Meta', 'React', 'AI', 'LLM', 'open-source'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 4 — RESEARCH
    // =========================================================================
    const research = [
        {
            title: 'NUST AI Lab Research Assistantship',
            organization: 'NUST Artificial Intelligence Research Centre (NUST-AIRC)',
            description: 'RAs join active NLP, Computer Vision, and RL projects, attend weekly lab meetings, run experiments, assist with literature reviews, and co-author papers targeting NeurIPS, ICML, and CVPR. Strong publication support from senior researchers and faculty.',
            category_id: 4, category_name: 'Research',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(30), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 25,000/month',
            duration: '6 months (renewable)',
            required_skills: ['Python', 'PyTorch', 'Machine Learning', 'Research Writing'],
            eligibility: 'BS 3rd/4th year or MS students in CS/DS/EE. CGPA ≥ 3.2.',
            application_link: '',
            tags: ['AI', 'NLP', 'computer-vision', 'publication', 'NUST'], posted_by: by,
        },
        {
            title: 'NUST Energy Research Lab — RA (Renewable Energy)',
            organization: 'NUST School of Electrical Engineering (SEECS)',
            description: 'The Energy Research Lab recruits RAs for projects on solar micro-grids, battery storage optimisation, and smart grid communication. RAs run MATLAB simulations, assist with lab experiments, and contribute to IEEE Transactions journal papers.',
            category_id: 4, category_name: 'Research',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(95), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 20,000/month',
            duration: '6 months',
            required_skills: ['MATLAB', 'Power Systems', 'Circuit Analysis', 'LaTeX'],
            eligibility: 'BS 3rd/4th year or MS EE students. CGPA ≥ 3.0.',
            application_link: '',
            tags: ['renewable-energy', 'IEEE', 'MATLAB', 'simulation', 'NUST'], posted_by: by,
        },
        {
            title: 'LUMS Centre for Economic Research — RA',
            organization: 'LUMS (Lahore University of Management Sciences)',
            description: "LUMS Centre for Economic Research hires undergraduate RAs from any Pakistani university for empirical micro-economics, development economics, and labour market research. RAs run regressions, clean survey data, and contribute to working papers.",
            category_id: 4, category_name: 'Research',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(180), opp_mode: 'hybrid', location: 'Lahore / Remote',
            is_paid: true, stipend: 'PKR 18,000/month',
            duration: '4 months',
            required_skills: ['Stata or R', 'Excel', 'Econometrics', 'Academic Writing'],
            eligibility: 'Any Pakistani university student in Economics or Social Sciences.',
            application_link: 'https://cer.lums.edu.pk',
            tags: ['economics', 'development', 'data', 'LUMS'], posted_by: by,
        },
        {
            title: 'UNESCO Youth Research Grant — Digital Futures',
            organization: 'UNESCO Pakistan',
            description: 'Grants of up to USD 5,000 for student-led research on Digital Futures: digital inclusion, AI ethics, online misinformation, and digital skills gaps in Pakistan. Selected findings appear in UNESCO global reports and policy briefs.',
            category_id: 4, category_name: 'Research',
            dept_id: 4, dept_name: 'Media Studies',
            deadline: d(100), opp_mode: 'remote', location: 'Remote / Pakistan',
            is_paid: true, stipend: 'Up to USD 5,000 research grant',
            duration: '6 months',
            required_skills: ['Research Methodology', 'Data Analysis', 'Academic Writing'],
            eligibility: 'Pakistani students aged 18–30. Individual or teams of 2.',
            application_link: 'https://www.unesco.org/pakistan',
            tags: ['UNESCO', 'social-research', 'digital', 'grant', 'policy'], posted_by: by,
        },
        {
            title: 'PIDE Research Associate — Pakistan Economy',
            organization: 'Pakistan Institute of Development Economics (PIDE)',
            description: "PIDE's flagship RA programme places students inside its macro-economics and public-policy teams. RAs assist senior economists with policy briefs, data collection, and research submitted to Pakistan's Ministry of Finance and the World Bank.",
            category_id: 4, category_name: 'Research',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(210), opp_mode: 'on-campus', location: 'Islamabad, Pakistan',
            is_paid: true, stipend: 'PKR 22,000/month',
            duration: '6 months',
            required_skills: ['Economics', 'SPSS or Stata', 'Policy Writing', 'MS Excel'],
            eligibility: 'BS/MS students or recent graduates in Economics or related fields.',
            application_link: 'https://pide.org.pk/careers',
            tags: ['economics', 'policy', 'World-Bank', 'PIDE', 'government'], posted_by: by,
        },
        {
            title: 'WWF Pakistan — Environmental Data Research Intern',
            organization: 'WWF Pakistan (World Wide Fund for Nature)',
            description: 'WWF Pakistan seeks a research intern for biodiversity monitoring, deforestation analysis using satellite imagery, and climate vulnerability assessments for northern Pakistan. Work involves QGIS, Python, and field-data management.',
            category_id: 4, category_name: 'Research',
            dept_id: 5, dept_name: 'Mathematics',
            deadline: d(90), opp_mode: 'hybrid', location: 'Islamabad / Field',
            is_paid: false, stipend: 'Unpaid (travel allowance provided)',
            duration: '3 months',
            required_skills: ['QGIS', 'Python', 'Remote Sensing', 'Data Cleaning'],
            eligibility: 'Students in Environmental Science, Geography, CS, or Mathematics.',
            application_link: 'https://www.wwfpak.org/careers',
            tags: ['environment', 'GIS', 'biodiversity', 'climate', 'Pakistan'], posted_by: by,
        },
        {
            title: 'IBA Karachi — Behavioural Economics Research Project',
            organization: 'IBA Karachi (Institute of Business Administration)',
            description: 'IBA invites students from any Pakistani university to join a 4-month research project studying consumer behaviour and financial decision-making in low-income households. Mixed-method research: surveys, field experiments, and statistical analysis.',
            category_id: 4, category_name: 'Research',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(140), opp_mode: 'hybrid', location: 'Karachi / Remote',
            is_paid: true, stipend: 'PKR 15,000/month',
            duration: '4 months',
            required_skills: ['SPSS or R', 'Survey Design', 'Qualitative Analysis'],
            eligibility: 'BS/MS students in Economics, Psychology, or Business. Any university.',
            application_link: 'https://www.iba.edu.pk/research',
            tags: ['behavioural-economics', 'IBA', 'Karachi', 'field-research'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 5 — COURSES / BOOTCAMPS
    // =========================================================================
    const courses = [
        {
            title: 'Devsinc Full-Stack Web Dev Bootcamp',
            organization: 'Devsinc',
            description: '8-week intensive MERN-stack bootcamp. Cohorts of 20 build two deployed projects with senior engineer code reviews. Top graduates receive direct job offers at Devsinc (engineering team). Pre-selection coding test required.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(30), opp_mode: 'remote', location: 'Remote',
            is_paid: false, stipend: 'Free (coding test required)',
            duration: '8 weeks (4 hours/day)',
            required_skills: ['HTML/CSS', 'Basic JavaScript', 'Git'],
            eligibility: 'CS/SE students or recent graduates. Pass online coding assessment.',
            application_link: 'https://devsinc.com/bootcamp',
            tags: ['MERN', 'full-stack', 'bootcamp', 'job-offer', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Stanford Machine Learning Specialisation — Financial Aid',
            organization: 'Stanford University / Coursera',
            description: "Andrew Ng's landmark ML Specialisation (3 courses: supervised learning, unsupervised learning, recommenders, RL) is available with 100% Coursera Financial Aid. Aid approved within 15 days. Globally recognised; listed by top Pakistani employers.",
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(125), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via Financial Aid',
            duration: '3 months (self-paced)',
            required_skills: ['Python Basics', 'Linear Algebra', 'Calculus Basics'],
            eligibility: 'Anyone with financial need. Write a short essay on the Coursera financial aid page.',
            application_link: 'https://www.coursera.org/specializations/machine-learning-introduction',
            tags: ['ML', 'Stanford', 'free', 'certificate', 'Python', 'Andrew-Ng'], posted_by: by,
        },
        {
            title: 'AWS re:Start — Free Cloud Computing Programme',
            organization: 'Amazon Web Services (AWS)',
            description: 'AWS re:Start is a free 12-week full-time cloud programme. Covers cloud fundamentals, Python, Linux, networking, and prepares students for the AWS Certified Cloud Practitioner exam (exam fee paid by AWS). Job placement support through AWS hiring partners in Pakistan.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(45), opp_mode: 'on-campus', location: 'Islamabad / Lahore / Karachi',
            is_paid: false, stipend: 'Free + AWS exam voucher (USD 100)',
            duration: '12 weeks (full-time)',
            required_skills: ['No prior cloud experience needed'],
            eligibility: 'Any university student or recent graduate. Full-time commitment for 12 weeks.',
            application_link: 'https://aws.amazon.com/training/restart',
            tags: ['cloud', 'AWS', 'free', 'certification', 'job-placement'], posted_by: by,
        },
        {
            title: 'Meta Frontend Developer Professional Certificate',
            organization: 'Meta / Coursera',
            description: 'Official 9-course programme by Meta engineers: HTML, CSS, React, UI/UX principles, version control, and a capstone React app. Financial aid available. Certificate widely recognised by Pakistani and international employers.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(160), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via Financial Aid',
            duration: '7 months (self-paced)',
            required_skills: ['Basic Computer Literacy'],
            eligibility: 'Anyone. Apply for financial aid on Coursera.',
            application_link: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
            tags: ['React', 'frontend', 'Meta', 'certificate', 'beginner-friendly'], posted_by: by,
        },
        {
            title: 'Google UX Design Professional Certificate',
            organization: 'Google / Coursera',
            description: "7 self-paced courses taught by Google's own designers covering design thinking, wireframing, prototyping in Figma, and usability testing. Financial aid available. No prior design experience needed. Globally recognised certificate.",
            category_id: 5, category_name: 'Course',
            dept_id: 4, dept_name: 'Media Studies',
            deadline: d(200), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via Financial Aid',
            duration: '6 months (self-paced)',
            required_skills: ['No prior experience needed'],
            eligibility: 'Open to anyone. Apply for Coursera Financial Aid.',
            application_link: 'https://www.coursera.org/professional-certificates/google-ux-design',
            tags: ['UX', 'Figma', 'design', 'Google', 'certificate'], posted_by: by,
        },
        {
            title: 'Telenor Academy — Digital Skills Certification',
            organization: 'Telenor Pakistan',
            description: 'Free 6-week online certification covering Digital Marketing, Data Analytics, Cyber Security basics, and App Development. Each track is 12 hours of video + assignments + a graded project. Widely recognised by Pakistani employers.',
            category_id: 5, category_name: 'Course',
            dept_id: 6, dept_name: 'Psychology',
            deadline: d(80), opp_mode: 'remote', location: 'Online',
            is_paid: false, stipend: 'Free certification',
            duration: '6 weeks (self-paced)',
            required_skills: [],
            eligibility: 'All Pakistani university students. CNIC required for registration.',
            application_link: 'https://telenor.com.pk/telenor-academy',
            tags: ['digital-skills', 'free', 'certification', 'all-disciplines', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Google Data Analytics Professional Certificate',
            organization: 'Google / Coursera',
            description: '8-course programme by Google analysts covering data cleaning (SQL, spreadsheets), visualisation (Tableau, R), and a capstone case study. One of the most-enrolled certificates on Coursera. Financial aid covers full cost.',
            category_id: 5, category_name: 'Course',
            dept_id: 5, dept_name: 'Mathematics',
            deadline: d(95), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via Financial Aid',
            duration: '6 months (self-paced)',
            required_skills: ['Basic Math', 'Spreadsheet Familiarity'],
            eligibility: 'Open to everyone. Apply for Financial Aid on Coursera.',
            application_link: 'https://www.coursera.org/professional-certificates/google-data-analytics',
            tags: ['data-analytics', 'SQL', 'Tableau', 'R', 'Google', 'certificate'], posted_by: by,
        },
        {
            title: 'DeepLearning.AI Deep Learning Specialisation',
            organization: 'DeepLearning.AI / Coursera',
            description: "5-course deep learning specialisation by Andrew Ng: Neural Networks, CNNs, RNNs, Sequence Models, and Structuring ML Projects. Financial aid available. Strongly recommended for anyone pursuing ML engineering or AI research in Pakistan's growing tech sector.",
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(100), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via Financial Aid',
            duration: '4 months (self-paced)',
            required_skills: ['Python', 'NumPy', 'Basic ML knowledge'],
            eligibility: 'Anyone with Python basics. Financial aid available.',
            application_link: 'https://www.coursera.org/specializations/deep-learning',
            tags: ['deep-learning', 'CNN', 'RNN', 'Andrew-Ng', 'free', 'certificate'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 6 — EXCHANGE PROGRAMS
    // =========================================================================
    const exchangePrograms = [
        {
            title: 'Erasmus+ Exchange — TU Munich, Germany',
            organization: 'TU Munich & Erasmus+',
            description: 'One semester at TU Munich (top 50 globally for CS/Engineering). Erasmus+ grant covers tuition, EUR 600–800/month living allowance, and return flights. Courses in AI, robotics, or entrepreneurship. Credits transfer fully to NUST.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(140), opp_mode: 'on-campus', location: 'Munich, Germany',
            is_paid: true, stipend: 'EUR 600–800/month + travel grant',
            duration: '1 semester (5 months)',
            required_skills: ['IELTS 6.0+ or TOEFL 80+'],
            eligibility: '3rd or 4th year BS. CGPA ≥ 3.0. Nominated by NUST OAA office.',
            application_link: '',
            tags: ['Germany', 'Erasmus', 'Europe', 'exchange', 'fully-funded', 'AI'], posted_by: by,
        },
        {
            title: 'Japan JASSO Exchange — Kyoto University',
            organization: 'Japan Student Services Organisation (JASSO)',
            description: "JASSO's short-term exchange to Kyoto University — one of Japan's most prestigious institutions. Includes JPY 80,000/month JASSO stipend. World-class research in CS, robotics, quantum computing, and physics.",
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(60), opp_mode: 'on-campus', location: 'Kyoto, Japan',
            is_paid: true, stipend: 'JPY 80,000/month (JASSO)',
            duration: '1 semester',
            required_skills: ['TOEFL 72+ or IELTS 5.5+', 'Japanese A1 (preferred)'],
            eligibility: 'BS 3rd year+ in CS/EE/Sciences. CGPA ≥ 3.2.',
            application_link: '',
            tags: ['Japan', 'JASSO', 'Kyoto', 'stipend', 'exchange', 'robotics'], posted_by: by,
        },
        {
            title: 'China Scholarship Council (CSC) — Full Scholarship',
            organization: 'China Scholarship Council / Chinese Universities',
            description: 'Full scholarship for Pakistani students at top Chinese universities (Tsinghua, Peking, Fudan, USTC). Covers tuition, accommodation, health insurance, and monthly stipend. Available for BS, Master\'s, and PhD. Applied through HEC Pakistan.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(180), opp_mode: 'on-campus', location: 'Beijing / Shanghai / Hefei, China',
            is_paid: true, stipend: 'CNY 2,500–3,500/month + tuition + dorm',
            duration: "4 years (BS) / 2–3 years (Master's) / 3–4 years (PhD)",
            required_skills: ['Academic Excellence', 'English or Chinese Proficiency'],
            eligibility: 'Pakistani citizens under 35. CGPA ≥ 3.0. Apply via HEC.',
            application_link: 'https://www.hec.gov.pk/csc',
            tags: ['China', 'fully-funded', 'Tsinghua', 'BS', 'masters', 'PhD', 'HEC'], posted_by: by,
        },
        {
            title: 'South Korea POSTECH Exchange Program',
            organization: 'POSTECH (Pohang University of Science & Technology)',
            description: "POSTECH, ranked Asia's top 10 for science & technology, offers a one-semester exchange for CS and EE students. Advanced courses in semiconductor engineering, AI, and bioinformatics. On-campus dormitory accommodation included.",
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(110), opp_mode: 'on-campus', location: 'Pohang, South Korea',
            is_paid: false, stipend: 'Dorm provided (NUST tuition waiver)',
            duration: '1 semester',
            required_skills: ['English Proficiency', 'Strong Academic Standing'],
            eligibility: 'BS 3rd year+ in CS or EE. Apply through NUST OAA.',
            application_link: '',
            tags: ['South-Korea', 'Asia', 'POSTECH', 'AI', 'semiconductor'], posted_by: by,
        },
        {
            title: 'AIT Thailand Semester Exchange',
            organization: 'Asian Institute of Technology (AIT)',
            description: 'Semester exchange in Bangkok at AIT — students from 50+ countries. NUST waives home tuition. Strong research collaboration in Engineering and Environmental Science. Bangkok living costs lower than European exchanges.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(120), opp_mode: 'on-campus', location: 'Bangkok, Thailand',
            is_paid: false, stipend: 'NUST tuition waiver',
            duration: '1 semester',
            required_skills: ['IELTS 5.5+'],
            eligibility: 'BS 3rd year+. Good academic standing (no F grade).',
            application_link: '',
            tags: ['Asia', 'Thailand', 'exchange', 'engineering', 'environment'], posted_by: by,
        },
        {
            title: 'Turkey Mevlana Exchange — METU / Bogazici',
            organization: 'Council of Higher Education Turkey (YÖK)',
            description: "One or two semesters at Turkey's top universities (METU, ITU, Bogazici). Excellent engineering and social science departments. Credit transfer to NUST fully recognised. Istanbul is a vibrant, affordable city for students.",
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(45), opp_mode: 'on-campus', location: 'Ankara / Istanbul, Turkey',
            is_paid: false, stipend: 'NUST tuition waiver',
            duration: '1–2 semesters',
            required_skills: ['IELTS 5.5+'],
            eligibility: 'BS 2nd year+ in any discipline. CGPA ≥ 2.5.',
            application_link: '',
            tags: ['Turkey', 'METU', 'Bogazici', 'Europe', 'exchange'], posted_by: by,
        },
        {
            title: 'US Virtual Exchange — IVLP Youth Programme',
            organization: 'US Embassy Islamabad / State Department',
            description: 'The International Visitor Leadership Program (IVLP) Youth Exchange connects Pakistani students with US universities and community leaders for a 3-week virtual or in-person exchange on civic engagement, innovation, and entrepreneurship.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(35), opp_mode: 'remote', location: 'USA (Virtual / In-person)',
            is_paid: true, stipend: 'Fully funded if in-person (flights, hotels, meals)',
            duration: '3 weeks',
            required_skills: ['Leadership experience', 'English Proficiency'],
            eligibility: 'Pakistani students aged 18–25. Any discipline.',
            application_link: 'https://pk.usembassy.gov/education-culture/exchange-programs',
            tags: ['USA', 'IVLP', 'exchange', 'leadership', 'civic', 'fully-funded'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 7 — COMPETITIONS
    // =========================================================================
    const competitions = [
        {
            title: 'ICPC Asia Regionals 2026 — Lahore Site',
            organization: 'ACM-ICPC',
            description: 'Teams of 3 solve algorithmic problems in 5 hours at the ACM-ICPC Asia Regionals. Top teams qualify for the ICPC World Finals. NUST ACM Chapter provides practice sessions and travel grants for selected teams throughout the year.',
            category_id: 7, category_name: 'Competition',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(105), opp_mode: 'on-campus', location: 'UET Lahore',
            is_paid: false, stipend: 'Travel grant for top 3 NUST teams',
            duration: '1-day competition',
            required_skills: ['Competitive Programming', 'Algorithms', 'C++ or Java'],
            eligibility: 'Full-time students. Teams of exactly 3.',
            application_link: '',
            tags: ['competitive-programming', 'algorithms', 'ICPC', 'world-finals'], posted_by: by,
        },
        {
            title: 'Microsoft Imagine Cup 2026',
            organization: 'Microsoft',
            description: "World's premier student technology competition. Build a tech solution for a global challenge (healthcare, sustainability, education). National → Regional → World Finals (USD 100,000 prize). Pakistani teams have reached global rounds before.",
            category_id: 7, category_name: 'Competition',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(145), opp_mode: 'remote', location: 'Online → World Finals (Seattle)',
            is_paid: true, stipend: 'USD 100,000 (World Finals winner)',
            duration: '3 months qualifying + Finals',
            required_skills: ['Azure', 'AI/ML', 'Pitching', 'Any Tech Stack'],
            eligibility: 'Enrolled students aged 18+. Teams of 1–3.',
            application_link: 'https://imaginecup.microsoft.com',
            tags: ['global', 'Azure', 'AI', 'prize', 'impact', 'Microsoft'], posted_by: by,
        },
        {
            title: 'NUST Incubator Business Plan Competition (NIC)',
            organization: 'NUST Technology Incubator (NIC)',
            description: 'Annual competition where NUST student teams pitch startup ideas to VCs and industry experts. Top 10 teams get free co-working space. Winner receives PKR 2,000,000 seed funding + access to NIC mentorship network and legal/accounting support.',
            category_id: 7, category_name: 'Competition',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(150), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 2,000,000 seed funding (winner)',
            duration: '2-day final',
            required_skills: ['Business Planning', 'Financial Modelling', 'Pitching'],
            eligibility: 'NUST students only. Teams of 2–5.',
            application_link: '',
            tags: ['startup', 'seed-funding', 'entrepreneurship', 'NIC', 'NUST'], posted_by: by,
        },
        {
            title: 'CFA Institute Research Challenge — Pakistan',
            organization: 'CFA Society Pakistan',
            description: 'Annual global competition: university teams produce a professional equity research report on an assigned listed Pakistani company and present to a jury of CFA Charterholders. Winning team represents Pakistan at the global CFA Research Challenge.',
            category_id: 7, category_name: 'Competition',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(180), opp_mode: 'on-campus', location: 'Karachi / Islamabad',
            is_paid: false, stipend: 'Global winner: prestige + CFA resources',
            duration: '3 months research + 1-day final',
            required_skills: ['Financial Modelling', 'DCF Valuation', 'Report Writing', 'Excel'],
            eligibility: 'University students in Finance, Economics, or Business. Teams of 3–5.',
            application_link: 'https://cfasociety.org.pk/research-challenge',
            tags: ['finance', 'equity-research', 'CFA', 'global', 'valuation'], posted_by: by,
        },
        {
            title: 'Ericsson Innovation Awards 2026',
            organization: 'Ericsson',
            description: "Ericsson's global student competition challenges teams to develop innovative 5G/IoT solutions. Pakistani university teams have placed in the global top 20. Finalists present to Ericsson leadership and receive mentorship from Ericsson engineers.",
            category_id: 7, category_name: 'Competition',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(210), opp_mode: 'remote', location: 'Online → Global Finals (Stockholm)',
            is_paid: true, stipend: 'EUR 10,000 (Global winner)',
            duration: '6 months',
            required_skills: ['5G', 'IoT', 'Innovation', 'Prototype Development'],
            eligibility: 'University students worldwide. Teams of 3–5.',
            application_link: 'https://www.ericsson.com/en/careers/university/innovation-awards',
            tags: ['5G', 'IoT', 'Ericsson', 'global', 'telecom'], posted_by: by,
        },
        {
            title: 'P&G CEO Challenge — Pakistan',
            organization: 'Procter & Gamble Pakistan',
            description: "P&G's flagship university competition: teams solve a real business problem for one of P&G's brands in Pakistan. Online submission → finals at P&G HQ. Winners receive PKR 100,000 + fast-track interview for internship.",
            category_id: 7, category_name: 'Competition',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(155), opp_mode: 'hybrid', location: 'Karachi (Finals)',
            is_paid: true, stipend: 'PKR 100,000 (winners) + internship fast-track',
            duration: '4 weeks',
            required_skills: ['Case Analysis', 'Strategy', 'Presentation', 'Teamwork'],
            eligibility: 'Penultimate or final year students. Any discipline. Teams of 4.',
            application_link: 'https://www.pg.com.pk/careers',
            tags: ['FMCG', 'business-case', 'strategy', 'P&G', 'internship'], posted_by: by,
        },
        {
            title: 'IEEE Robotics Competition — Pakistan Regional',
            organization: 'IEEE Pakistan Section',
            description: 'Annual robotics design competition where teams build autonomous robots to complete a task defined in the rulebook. Categories: line-following, maze-solver, and open-category. Top team advances to the IEEE Region 10 conference.',
            category_id: 7, category_name: 'Competition',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(200), opp_mode: 'on-campus', location: 'NUST / UET Lahore',
            is_paid: true, stipend: 'PKR 50,000 + IEEE Region 10 trip',
            duration: '1 day',
            required_skills: ['Embedded Systems', 'C Programming', 'Sensor Integration'],
            eligibility: 'EE / Mechatronics / CS students in Pakistani universities. Teams of 3.',
            application_link: '',
            tags: ['robotics', 'IEEE', 'autonomous', 'competition', 'engineering'], posted_by: by,
        },
    ];

    // =========================================================================
    //  CATEGORY 8 — WORKSHOPS
    // =========================================================================
    const workshops = [
        {
            title: 'GDSC NUST — Google Technologies Workshop Series',
            organization: 'Google Developer Student Clubs (GDSC) NUST',
            description: 'Semester-long workshop series covering Flutter, Firebase, Google Cloud, and TensorFlow Lite. Each session is 3 hours with hands-on labs. Attendees build and deploy a real project by the series end. Google swag for top contributors.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(90), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'Free',
            duration: '8 sessions (1 per week)',
            required_skills: ['Basic Programming'],
            eligibility: 'Open to all NUST students.',
            application_link: '',
            tags: ['Google', 'Flutter', 'Firebase', 'cloud', 'free', 'GDSC'], posted_by: by,
        },
        {
            title: 'AWS Cloud Fundamentals Technical Workshop',
            organization: 'Amazon Web Services (AWS)',
            description: 'One-day workshop by AWS Solutions Architects covering EC2, S3, Lambda, and RDS. Attendees get USD 50 AWS credits for live labs. Certificate of attendance issued by AWS. Held at partner universities — register for NUST.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(100), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'Free + USD 50 AWS credits',
            duration: '1 day (8 hours)',
            required_skills: ['Basic Linux', 'Networking Concepts'],
            eligibility: 'Any university student. Bring a laptop.',
            application_link: 'https://aws.amazon.com/training/events',
            tags: ['AWS', 'cloud', 'hands-on', 'free', 'certificate'], posted_by: by,
        },
        {
            title: 'IEEE NUST — Robotics & Embedded Systems Workshop',
            organization: 'IEEE Pakistan Section / NUST',
            description: 'Two-day hands-on workshop: robot programming with Arduino and ROS (Robot Operating System). Participants build a line-following robot and a simple arm controller. All components provided on-site. IEEE membership not required.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: d(55), opp_mode: 'on-campus', location: 'NUST SEECS, Islamabad',
            is_paid: false, stipend: 'Free (limited to 40 seats)',
            duration: '2 days (16 hours)',
            required_skills: ['Basic Electronics', 'C Programming'],
            eligibility: 'EE, Mechatronics, or CS students. 2nd year and above.',
            application_link: '',
            tags: ['robotics', 'Arduino', 'ROS', 'IEEE', 'embedded'], posted_by: by,
        },
        {
            title: 'UN Youth Forum — SDGs & Advocacy Workshop',
            organization: 'United Nations Pakistan (UNDP)',
            description: 'Full-day UN-facilitated workshop on SDGs, advocacy skills, and youth leadership. Participants develop campus action plans. UNDP Pakistan certificate issued. Strong networking with development-sector professionals.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 6, dept_name: 'Psychology',
            deadline: d(80), opp_mode: 'on-campus', location: 'Islamabad',
            is_paid: false, stipend: 'Free',
            duration: '1 day (8 hours)',
            required_skills: ['Public Speaking Interest', 'Leadership Interest'],
            eligibility: 'All Pakistani university students. Limited to 60 seats — apply early.',
            application_link: 'https://www.pk.undp.org/youth',
            tags: ['UN', 'SDGs', 'leadership', 'advocacy', 'certificate', 'UNDP'], posted_by: by,
        },
        {
            title: 'Startup Weekend NUST — 54-Hour Startup Bootcamp',
            organization: 'Techstars / NUST Entrepreneurship Centre',
            description: "The world's leading startup event at NUST. Pitch Friday evening, form a team, validate with real customers, and demo a working MVP to judges Sunday. Coaches from Google, Careem, and Systems Limited mentor throughout.",
            category_id: 8, category_name: 'Workshop',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(125), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'PKR 500 registration fee only',
            duration: '54 hours (Fri evening – Sun evening)',
            required_skills: ['Entrepreneurial Mindset', 'Design / Code / Business (any)'],
            eligibility: 'Open to all university students and recent graduates.',
            application_link: 'https://startupweekend.org',
            tags: ['startup', 'entrepreneurship', 'MVP', 'Techstars', 'weekend'], posted_by: by,
        },
        {
            title: 'Accenture Future Talent — Digital Skills Workshop',
            organization: 'Accenture Pakistan',
            description: "Accenture's half-day workshop on Agile project management, data-driven decision making, and digital transformation strategy. Run by Accenture MDs. Participants complete a mini case study and receive a LinkedIn digital badge. Fast-tracks into Accenture campus hiring.",
            category_id: 8, category_name: 'Workshop',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: d(160), opp_mode: 'on-campus', location: 'Karachi / Islamabad',
            is_paid: false, stipend: 'Free (LinkedIn digital badge)',
            duration: '4 hours',
            required_skills: ['Business Basics', 'Communication'],
            eligibility: 'Penultimate and final year students. All disciplines.',
            application_link: 'https://www.accenture.com/pk-en/careers/students',
            tags: ['Accenture', 'Agile', 'digital', 'LinkedIn-badge', 'hiring'], posted_by: by,
        },
        {
            title: 'Ignite DigiSkills — Freelancing & Digital Marketing',
            organization: 'Ignite (National Technology Fund) Pakistan',
            description: "Pakistan's largest government-funded digital skills programme. Courses include Freelancing, Digital Marketing, E-commerce, Graphic Design, and SEO. Over 2 million Pakistanis enrolled. Free certificate. Designed to enable earning from home.",
            category_id: 8, category_name: 'Workshop',
            dept_id: 4, dept_name: 'Media Studies',
            deadline: d(210), opp_mode: 'remote', location: 'Online',
            is_paid: false, stipend: 'Free',
            duration: '3 months (self-paced, 2 hrs/week)',
            required_skills: ['Basic Internet Usage'],
            eligibility: 'Any Pakistani citizen above 14 years.',
            application_link: 'https://digiskills.pk',
            tags: ['freelancing', 'digital-marketing', 'free', 'government', 'Pakistan'], posted_by: by,
        },
        {
            title: 'Microsoft AI Skills Initiative — Free Azure AI Training',
            organization: 'Microsoft (LinkedIn Learning + Azure)',
            description: "Microsoft's global initiative offers free AI and cloud training on LinkedIn Learning. Covers Azure AI Fundamentals, Responsible AI, and GitHub Copilot. Completion unlocks a free Microsoft Certified: Azure AI Fundamentals exam voucher (USD 165 value).",
            category_id: 8, category_name: 'Workshop',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: d(180), opp_mode: 'remote', location: 'Online',
            is_paid: false, stipend: 'Free + Azure exam voucher (USD 165)',
            duration: '40 hours (self-paced)',
            required_skills: ['Basic Computer Literacy'],
            eligibility: 'Anyone worldwide. Free Microsoft account required.',
            application_link: 'https://www.microsoft.com/en-us/ai/skills',
            tags: ['AI', 'Azure', 'Microsoft', 'free', 'certificate', 'exam-voucher'], posted_by: by,
        },
    ];

    // =========================================================================
    //  Insert all
    // =========================================================================
    const all = await Opportunity.insertMany([
        ...internships, ...scholarships, ...hackathons,
        ...research, ...courses, ...exchangePrograms,
        ...competitions, ...workshops,
    ]);
    console.log(`✔ Created ${all.length} opportunities`);

    // Notify demo student
    const notifs = all.map(o => ({
        user_id: student._id,
        opp_id:  o._id,
        message: `New opportunity posted: ${o.title}`,
        is_read: false,
    }));
    await Notification.insertMany(notifs);
    console.log(`✔ Created ${notifs.length} notifications`);

    const counts = {};
    all.forEach(o => { counts[o.category_name] = (counts[o.category_name] || 0) + 1; });
    console.log('\n📊 Opportunities per category:');
    Object.entries(counts).forEach(([cat, n]) => console.log(`   ${cat.padEnd(20)} ${n}`));
    console.log(`\n   TOTAL: ${all.length} opportunities`);

    console.log('\n✅ Seed complete!');
    console.log('   Admin   → admin@campus.edu      / admin123');
    console.log('   Student → student@seecs.edu.pk  / student123');

    await mongoose.disconnect();
}

seed().catch(err => { console.error('Seed failed:', err); process.exit(1); });
