/**
 * MongoDB seed script — 5-6 opportunities per category (8 categories, ~48 total)
 * Run: node database/seed.mongo.js
 *
 * Category IDs (matches backend/config/constants.js):
 *   1-Internship  2-Scholarship  3-Hackathon  4-Research
 *   5-Course      6-Exchange     7-Competition 8-Workshop
 */
require('dotenv').config({ path: require('path').resolve(__dirname, '../backend/.env') });
const mongoose = require('mongoose');
const bcrypt   = require('bcrypt');

const User             = require('../backend/models/User');
const Opportunity      = require('../backend/models/Opportunity');
const SavedOpportunity = require('../backend/models/SavedOpportunity');
const Notification     = require('../backend/models/Notification');

const future = days => new Date(Date.now() + days * 86_400_000);

async function seed() {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✔ Connected to MongoDB');

    await Promise.all([
        User.deleteMany({}), Opportunity.deleteMany({}),
        SavedOpportunity.deleteMany({}), Notification.deleteMany({}),
    ]);
    console.log('✔ Cleared existing data');

    // ── Users ────────────────────────────────────────────────────────────────
    const [admin, student] = await User.insertMany([
        { user_name: 'admin',        email: 'admin@campus.edu',      password_hash: await bcrypt.hash('admin123',   10), role_id: 1, dept_id: 1, dept_name: 'Computer Science' },
        { user_name: 'demo_student', email: 'student@seecs.edu.pk',  password_hash: await bcrypt.hash('student123', 10), role_id: 2, dept_id: 1, dept_name: 'Computer Science' },
    ]);
    const by = admin._id;
    console.log('✔ Created users');

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 1 — INTERNSHIPS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const internships = [
        {
            title: 'Google Summer of Code 2025',
            organization: 'Google',
            description: 'GSoC is a global programme that connects university students with open-source organisations for a 3-month paid coding project. Students are mentored by experienced engineers, contribute to widely used software, and build a strong public portfolio on GitHub.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(28), opp_mode: 'remote', location: 'Remote (Global)',
            is_paid: true, stipend: 'USD 3,000 – 6,600 (lump sum)',
            duration: '3 months (May – Aug)',
            required_skills: ['Git', 'Open Source', 'Python / C++ / JavaScript'],
            eligibility: 'Enrolled university students aged 18+. At least one open-source contribution.',
            application_link: 'https://summerofcode.withgoogle.com',
            tags: ['open-source', 'coding', 'mentorship', 'remote'], posted_by: by,
        },
        {
            title: 'Microsoft Explore Internship',
            organization: 'Microsoft',
            description: 'A 12-week internship for freshmen and sophomores exploring software engineering and programme management. Interns ship real features in Microsoft 365, Azure, or Teams, attend senior-leader Q&As, and complete a team design challenge.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(35), opp_mode: 'hybrid', location: 'Redmond, WA (Hybrid)',
            is_paid: true, stipend: 'USD 7,000/month + relocation',
            duration: '12 weeks (June – Aug)',
            required_skills: ['C#', '.NET', 'Azure', 'Data Structures', 'Algorithms'],
            eligibility: 'Freshman or sophomore in CS/related field. CGPA ≥ 3.2.',
            application_link: 'https://careers.microsoft.com',
            tags: ['cloud', 'product', 'global'], posted_by: by,
        },
        {
            title: 'Systems Limited Graduate Internship',
            organization: 'Systems Limited',
            description: 'Pakistan\'s largest IT exporter embeds interns directly into product teams building fintech, ERP, and digital-transformation solutions for global clients. Structured 3-month programme with mentorship, tech talks, and a pre-placement offer for top performers.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(18), opp_mode: 'on-campus', location: 'Lahore, Pakistan',
            is_paid: true, stipend: 'PKR 40,000/month',
            duration: '3 months',
            required_skills: ['Java', 'Spring Boot', 'SQL', 'REST APIs'],
            eligibility: 'Final-year or recently graduated BS CS/SE/IT students. CGPA ≥ 3.0.',
            application_link: 'https://www.systemsltd.com/careers',
            tags: ['fintech', 'enterprise', 'pre-placement'], posted_by: by,
        },
        {
            title: 'Careem Product & Engineering Internship',
            organization: 'Careem (Uber)',
            description: 'Join the super-app trusted by 50 million users. Engineering interns are embedded in squads working on ride-hailing, food delivery, or fintech features. Expect real sprint planning, code reviews, and a project demo to VP Engineering at the end.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(21), opp_mode: 'hybrid', location: 'Karachi / Remote',
            is_paid: true, stipend: 'PKR 65,000/month',
            duration: '3 months',
            required_skills: ['Kotlin', 'Node.js', 'Microservices', 'AWS'],
            eligibility: 'Penultimate or final year CS/SE. Mobile or backend experience required.',
            application_link: 'https://careem.com/careers',
            tags: ['super-app', 'mobile', 'backend', 'MENA'], posted_by: by,
        },
        {
            title: 'Arbisoft Summer Internship',
            organization: 'Arbisoft',
            description: 'Work on US-based client SaaS products with senior engineers at one of Pakistan\'s fastest-growing software companies. Bi-weekly learning sessions and a demo day at the end. Strong performers receive return offers.',
            category_id: 1, category_name: 'Internship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(14), opp_mode: 'hybrid', location: 'Lahore, Pakistan',
            is_paid: true, stipend: 'PKR 35,000/month',
            duration: '2 months (June – July)',
            required_skills: ['React', 'Django', 'Python', 'PostgreSQL'],
            eligibility: '3rd or 4th year CS/SE. Must have completed at least one web project.',
            application_link: 'https://arbisoft.com/careers',
            tags: ['web-development', 'startup', 'client-work'], posted_by: by,
        },
        {
            title: 'Jazz Digital Innovation Internship',
            organization: 'Jazz (Veon)',
            description: 'Pakistan\'s largest telecom is recruiting CS/EE interns for its Digital & AI division. Interns work on predictive churn models, network analytics dashboards, and AI-driven customer care. Exposure to petabyte-scale real-time data pipelines.',
            category_id: 1, category_name: 'Internship',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(12), opp_mode: 'on-campus', location: 'Islamabad, Pakistan',
            is_paid: true, stipend: 'PKR 45,000/month',
            duration: '6 weeks',
            required_skills: ['Python', 'SQL', 'Machine Learning', 'Data Analytics'],
            eligibility: '3rd/4th year EE, CS, or DS students. Data analysis tools experience preferred.',
            application_link: 'https://jazz.com.pk/careers',
            tags: ['telecom', 'AI', 'data', 'Pakistan'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 2 — SCHOLARSHIPS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const scholarships = [
        {
            title: 'HEC Need-Based Scholarship 2025–26',
            organization: 'Higher Education Commission Pakistan',
            description: 'Financial assistance for deserving students from low-income families enrolled in recognised HEIs. Covers tuition fees, hostel charges, and a monthly stipend for up to 4 years.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(45), opp_mode: 'on-campus', location: 'Pakistan (All HEIs)',
            is_paid: true, stipend: 'PKR 60,000/year + tuition waiver',
            duration: 'Up to 4 years (renewable)',
            required_skills: [],
            eligibility: 'Pakistani BS students. Family income < PKR 45,000/month. CGPA ≥ 2.5.',
            application_link: 'https://www.hec.gov.pk/needbased',
            tags: ['need-based', 'undergraduate', 'government'], posted_by: by,
        },
        {
            title: 'DAAD Scholarship — Study in Germany 2026',
            organization: 'DAAD (German Academic Exchange Service)',
            description: 'Full scholarship for outstanding Pakistani students pursuing Master\'s or PhD at top German universities. Covers tuition, monthly allowance (EUR 934), health insurance, travel, and German language courses.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(60), opp_mode: 'on-campus', location: 'Germany',
            is_paid: true, stipend: 'EUR 934/month + extras',
            duration: '1–2 years (Master\'s) / 3 years (PhD)',
            required_skills: ['Academic Excellence', 'Research Proposal', 'English/German Proficiency'],
            eligibility: 'BS graduates CGPA ≥ 3.0. Max age 32 (Master\'s) / 35 (PhD).',
            application_link: 'https://www.daad.de/en',
            tags: ['Germany', 'masters', 'PhD', 'fully-funded'], posted_by: by,
        },
        {
            title: 'Commonwealth Scholarship — United Kingdom',
            organization: 'Commonwealth Scholarship Commission',
            description: 'Fully funded scholarship for Commonwealth citizens to pursue Master\'s and PhD degrees at UK universities. Includes tuition, living allowance (GBP 1,236/month), return airfare, and thesis grant.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(55), opp_mode: 'on-campus', location: 'United Kingdom',
            is_paid: true, stipend: 'GBP 1,236/month + tuition + airfare',
            duration: '1 year (Master\'s) / 3 years (PhD)',
            required_skills: ['First/Upper-Second Class Degree', 'IELTS 6.5+'],
            eligibility: 'Pakistani citizens. Upper-second class or first class Bachelor\'s.',
            application_link: 'https://www.hec.gov.pk/commonwealth',
            tags: ['UK', 'fully-funded', 'development', 'masters'], posted_by: by,
        },
        {
            title: 'Aga Khan Foundation International Scholarship',
            organization: 'Aga Khan Foundation',
            description: 'Postgraduate scholarships for outstanding students from selected developing countries who have no other means of funding. Structured as 50% grant + 50% loan for Master\'s and PhD programs worldwide.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(50), opp_mode: 'on-campus', location: 'International',
            is_paid: true, stipend: 'Partial grant (50%) + 50% loan',
            duration: 'Duration of postgraduate program',
            required_skills: ['Academic Excellence', 'Community Service'],
            eligibility: 'Pakistani citizens. Outstanding merit and genuine financial need.',
            application_link: 'https://www.akdn.org/AKF_Scholarships',
            tags: ['postgraduate', 'merit-need', 'international'], posted_by: by,
        },
        {
            title: 'Teach For Pakistan Fellowship',
            organization: 'Teach For Pakistan',
            description: 'Two-year Fellowship placing talented graduates as full-time teachers in low-income schools in Karachi, Lahore, and Islamabad. Includes intensive training, leadership development, and an alumni network of impact-driven professionals.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(42), opp_mode: 'on-campus', location: 'Karachi / Lahore / Islamabad',
            is_paid: true, stipend: 'PKR 45,000/month',
            duration: '2 years',
            required_skills: ['Communication', 'Leadership', 'Resilience'],
            eligibility: 'Graduates (within 3 years). Any discipline. CGPA ≥ 3.0.',
            application_link: 'https://teachforpakistan.org/fellowship',
            tags: ['fellowship', 'education', 'social-impact', 'leadership'], posted_by: by,
        },
        {
            title: 'Atlas Corps Global Leadership Fellowship',
            organization: 'Atlas Corps (Washington DC)',
            description: 'Atlas Corps places skilled emerging leaders at US-based nonprofits for 12–18 month paid fellowships. Past Pakistani fellows served at Amnesty International, CARE, and Brookings. Includes health insurance and access to a 1,000+ global alumni network.',
            category_id: 2, category_name: 'Scholarship',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(50), opp_mode: 'on-campus', location: 'Washington DC, USA',
            is_paid: true, stipend: 'USD 1,500/month + health insurance',
            duration: '12–18 months',
            required_skills: ['Leadership', 'English Proficiency', 'Community Work'],
            eligibility: 'Graduates aged 21–35. Min 2 years experience in social sector.',
            application_link: 'https://atlascorps.org/apply',
            tags: ['fellowship', 'USA', 'nonprofit', 'leadership'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 3 — HACKATHONS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const hackathons = [
        {
            title: 'NUST AI Hackathon — Build the Future',
            organization: 'NUST Centre for Artificial Intelligence',
            description: '48-hour AI hackathon on campus with tracks in Healthcare, Climate, Education, and FinTech. Teams of 2–4 students. Winners receive a seed grant and mentorship from NUST industry partners. Top 3 teams pitch to a panel of VCs.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(9), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'Prize Pool: PKR 500,000',
            duration: '48 hours',
            required_skills: ['Python', 'Machine Learning', 'TensorFlow / PyTorch'],
            eligibility: 'All currently enrolled NUST students. Teams of 2–4.',
            application_link: '',
            tags: ['AI', 'machine-learning', '48-hour', 'prize'], posted_by: by,
        },
        {
            title: 'Telenor Digital Innovation Challenge',
            organization: 'Telenor Pakistan',
            description: 'Annual innovation challenge inviting university teams to pitch digital solutions for connectivity and digital inclusion. Online qualifying round → top 10 teams fly to Islamabad finals. Winner receives PKR 300,000 + internship offer.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(22), opp_mode: 'hybrid', location: 'Islamabad (Final) / Online',
            is_paid: true, stipend: 'PKR 300,000 + internship offer',
            duration: '3 weeks online + 2-day final',
            required_skills: ['Product Design', 'Business Modeling', 'Prototyping'],
            eligibility: 'University students from any discipline. Teams of 3.',
            application_link: 'https://telenor.com.pk/innovation-challenge',
            tags: ['telecom', 'innovation', 'startup', 'prize'], posted_by: by,
        },
        {
            title: 'GitHub Copilot Hackathon — AI-Assisted Dev',
            organization: 'GitHub',
            description: 'Build any project using GitHub Copilot and submit your repository. Judged on code quality, innovation, and real-world impact. Monthly rolling submissions. Great for open-source portfolio building.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(30), opp_mode: 'remote', location: 'Remote (Global)',
            is_paid: true, stipend: 'USD 5,000 monthly prize',
            duration: 'Rolling monthly',
            required_skills: ['Any Language', 'GitHub', 'GitHub Copilot'],
            eligibility: 'Any developer worldwide. Individual or team (max 4).',
            application_link: 'https://github.com/hackathon',
            tags: ['AI', 'GitHub', 'open-source', 'remote'], posted_by: by,
        },
        {
            title: 'NASA Space Apps Challenge — Pakistan',
            organization: 'NASA / SUPARCO',
            description: 'The world\'s largest annual hackathon, co-organised by NASA and local partner SUPARCO. Teams solve real space and Earth science challenges using NASA\'s open data. Local winners progress to NASA\'s global judging round. No aerospace background required.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(16), opp_mode: 'on-campus', location: 'Islamabad / Lahore / Karachi',
            is_paid: false, stipend: 'Global winner: NASA facility visit',
            duration: '2 days (48 hours)',
            required_skills: ['Data Visualisation', 'Python or JS', 'Creative Problem Solving'],
            eligibility: 'Any university student. Teams of 1–6. Any discipline welcome.',
            application_link: 'https://www.spaceappschallenge.org',
            tags: ['NASA', 'space', 'data', 'global', 'open-data'], posted_by: by,
        },
        {
            title: 'HackNUST — Inter-University Hackathon',
            organization: 'NUST ACM Student Chapter',
            description: 'Annual inter-university 36-hour hackathon hosted by NUST. Participants from across Pakistan compete in Fintech, Smart Cities, EdTech, and Health tracks. Mentors from Careem, Telenor, and NUST faculty are available throughout the event.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(11), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 150,000 total prizes',
            duration: '36 hours',
            required_skills: ['Any Tech Stack', 'Rapid Prototyping', 'Teamwork'],
            eligibility: 'Open to all Pakistani university students. Teams of 3–5.',
            application_link: '',
            tags: ['inter-university', 'fintech', 'EdTech', 'NUST'], posted_by: by,
        },
        {
            title: 'Meta Open Source Hackathon',
            organization: 'Meta (Facebook)',
            description: 'Meta\'s global hackathon for students to build projects using Meta\'s open-source stack: React, PyTorch, LLAMA, or Llama Index. Submissions are evaluated by Meta engineers. Top projects featured on Meta\'s open-source blog and developers receive Meta swag and gift cards.',
            category_id: 3, category_name: 'Hackathon',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(25), opp_mode: 'remote', location: 'Remote (Global)',
            is_paid: true, stipend: 'USD 2,000 gift cards + Meta swag',
            duration: '4 weeks (rolling submissions)',
            required_skills: ['React', 'PyTorch', 'LLMs', 'Open Source'],
            eligibility: 'University students worldwide. Individual or team (max 3).',
            application_link: 'https://developers.facebook.com/community',
            tags: ['Meta', 'React', 'AI', 'LLM', 'open-source'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 4 — RESEARCH  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const research = [
        {
            title: 'NUST AI Lab Research Assistantship',
            organization: 'NUST Artificial Intelligence Research Centre',
            description: 'RAs join active NLP, Computer Vision, and RL projects, attend weekly lab meetings, run experiments, assist with literature reviews, and co-author papers targeting NeurIPS, ICML, and CVPR. Strong publication support from senior researchers.',
            category_id: 4, category_name: 'Research',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(17), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 25,000/month',
            duration: '6 months (renewable)',
            required_skills: ['Python', 'PyTorch', 'Machine Learning', 'Research Writing'],
            eligibility: 'BS 3rd/4th year or MS students in CS/DS/EE. CGPA ≥ 3.2.',
            application_link: '',
            tags: ['AI', 'NLP', 'computer-vision', 'publication', 'lab'], posted_by: by,
        },
        {
            title: 'UNESCO Youth Research Grant — Digital Futures',
            organization: 'UNESCO Pakistan',
            description: 'Grants of up to USD 5,000 for small-scale student-led research on Digital Futures themes: digital inclusion, AI ethics, online misinformation, and digital skills gaps in Pakistan. Findings may appear in UNESCO global reports.',
            category_id: 4, category_name: 'Research',
            dept_id: 4, dept_name: 'Media Studies',
            deadline: future(38), opp_mode: 'remote', location: 'Remote / Pakistan',
            is_paid: true, stipend: 'Up to USD 5,000 research grant',
            duration: '6 months',
            required_skills: ['Research Methodology', 'Data Analysis', 'Academic Writing'],
            eligibility: 'Pakistani students aged 18–30. Individual or teams of 2.',
            application_link: 'https://www.unesco.org/pakistan',
            tags: ['UNESCO', 'social-research', 'digital', 'grant'], posted_by: by,
        },
        {
            title: 'NUST Energy Research Lab — RA (Renewable Energy)',
            organization: 'NUST School of Electrical Engineering',
            description: 'The Energy Research Lab is recruiting RAs for projects on solar micro-grids, battery storage optimisation, and smart grid communication protocols. RAs assist with MATLAB simulations, lab experiments, and literature reviews targeting IEEE Transactions journals.',
            category_id: 4, category_name: 'Research',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(20), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 20,000/month',
            duration: '6 months',
            required_skills: ['MATLAB', 'Power Systems', 'Circuit Analysis', 'LaTeX'],
            eligibility: 'BS 3rd/4th year or MS EE students. CGPA ≥ 3.0.',
            application_link: '',
            tags: ['renewable-energy', 'IEEE', 'simulation', 'lab'], posted_by: by,
        },
        {
            title: 'LUMS Centre for Economic Research — RA',
            organization: 'LUMS (Lahore University of Management Sciences)',
            description: 'The LUMS Centre for Economic Research hires undergraduate RAs from any Pakistani university to assist on empirical micro-economics, development economics, and labour market research. RAs run regressions, clean survey data, and contribute to working papers.',
            category_id: 4, category_name: 'Research',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(32), opp_mode: 'hybrid', location: 'Lahore / Remote',
            is_paid: true, stipend: 'PKR 18,000/month',
            duration: '4 months',
            required_skills: ['Stata or R', 'Excel', 'Econometrics', 'Academic Writing'],
            eligibility: 'Any Pakistani university student. Economics or Social Sciences preferred.',
            application_link: 'https://cer.lums.edu.pk',
            tags: ['economics', 'development', 'data', 'research'], posted_by: by,
        },
        {
            title: 'WWF Pakistan — Environmental Data Research Intern',
            organization: 'WWF Pakistan (World Wide Fund for Nature)',
            description: 'WWF Pakistan is seeking a research intern to assist with biodiversity monitoring, deforestation data analysis using satellite imagery, and climate vulnerability assessments for northern Pakistan. Work involves QGIS, Python, and field-data management.',
            category_id: 4, category_name: 'Research',
            dept_id: 5, dept_name: 'Mathematics',
            deadline: future(24), opp_mode: 'hybrid', location: 'Islamabad / Field',
            is_paid: false, stipend: 'Unpaid (stipend under review)',
            duration: '3 months',
            required_skills: ['QGIS', 'Python', 'Remote Sensing', 'Data Cleaning'],
            eligibility: 'Students in Environmental Science, Geography, CS, or Mathematics.',
            application_link: 'https://www.wwfpak.org/careers',
            tags: ['environment', 'GIS', 'biodiversity', 'climate'], posted_by: by,
        },
        {
            title: 'PIDE Research Associate — Pakistan Economy',
            organization: 'Pakistan Institute of Development Economics (PIDE)',
            description: 'PIDE\'s flagship Research Associate programme places top students inside its macro-economics and public-policy research teams. RAs assist senior economists with policy briefs, data collection, and literature for reports submitted to Pakistan\'s Ministry of Finance and World Bank.',
            category_id: 4, category_name: 'Research',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(40), opp_mode: 'on-campus', location: 'Islamabad, Pakistan',
            is_paid: true, stipend: 'PKR 22,000/month',
            duration: '6 months',
            required_skills: ['Economics', 'SPSS or Stata', 'Policy Writing', 'MS Excel'],
            eligibility: 'BS/MS students or recent graduates in Economics or related fields.',
            application_link: 'https://pide.org.pk/careers',
            tags: ['economics', 'policy', 'World-Bank', 'government'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 5 — COURSES / BOOTCAMPS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const courses = [
        {
            title: 'Devsinc Full-Stack Web Dev Bootcamp',
            organization: 'Devsinc',
            description: '8-week intensive MERN-stack bootcamp. Cohorts of 20 students build two deployed projects with senior engineer code reviews. Top graduates receive job offers at Devsinc. Pre-selection coding test required.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(8), opp_mode: 'remote', location: 'Remote',
            is_paid: false, stipend: 'Free (test required)',
            duration: '8 weeks (4 hours/day)',
            required_skills: ['HTML/CSS', 'Basic JavaScript', 'Git'],
            eligibility: 'CS/SE students or recent graduates. Pass online coding assessment.',
            application_link: 'https://devsinc.com/bootcamp',
            tags: ['MERN', 'full-stack', 'bootcamp', 'job-offer'], posted_by: by,
        },
        {
            title: 'Telenor Academy — Digital Skills Certification',
            organization: 'Telenor Pakistan',
            description: 'Free 6-week online certification covering Digital Marketing, Data Analytics, Cyber Security basics, and App Development. Each track is 12 hours of video + assignments + a graded project. Widely recognised by Pakistani employers.',
            category_id: 5, category_name: 'Course',
            dept_id: 6, dept_name: 'Psychology',
            deadline: future(15), opp_mode: 'remote', location: 'Online',
            is_paid: false, stipend: 'Free certification',
            duration: '6 weeks (self-paced)',
            required_skills: [],
            eligibility: 'All Pakistani university students. CNIC required.',
            application_link: 'https://telenor.com.pk/telenor-academy',
            tags: ['digital-skills', 'free', 'certification', 'all-disciplines'], posted_by: by,
        },
        {
            title: 'Stanford ML Specialisation — Coursera Financial Aid',
            organization: 'Stanford University / Coursera',
            description: 'Andrew Ng\'s landmark Machine Learning Specialisation (3 courses: supervised, unsupervised, and recommender systems) is available with 100% financial aid. Apply with a short essay explaining financial need. Aid is typically approved within 15 days.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(20), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via financial aid',
            duration: '3 months (self-paced)',
            required_skills: ['Python Basics', 'Linear Algebra', 'Calculus Basics'],
            eligibility: 'Anyone with financial need. Write a short essay on the Coursera financial aid page.',
            application_link: 'https://www.coursera.org/specializations/machine-learning-introduction',
            tags: ['ML', 'Stanford', 'free', 'certificate', 'Python'], posted_by: by,
        },
        {
            title: 'AWS Cloud Practitioner Scholarship — re:Start',
            organization: 'Amazon Web Services (AWS)',
            description: 'AWS re:Start is a free 12-week full-time cloud computing programme offered in partnership with AWS. Covers cloud fundamentals, Python, Linux, networking, and prepares students for the AWS Certified Cloud Practitioner exam (exam fee covered). Job placement support provided.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(30), opp_mode: 'on-campus', location: 'Islamabad / Lahore / Karachi',
            is_paid: false, stipend: 'Free + AWS exam voucher',
            duration: '12 weeks (full-time)',
            required_skills: ['No prior cloud experience needed'],
            eligibility: 'Any university student or recent graduate. Must commit full-time for 12 weeks.',
            application_link: 'https://aws.amazon.com/training/restart',
            tags: ['cloud', 'AWS', 'free', 'certification', 'job-placement'], posted_by: by,
        },
        {
            title: 'Meta Frontend Developer Professional Certificate',
            organization: 'Meta / Coursera',
            description: 'Official 9-course programme by Meta engineers teaching HTML, CSS, React, UI/UX principles, and version control. Includes a capstone project building a full React app. Financial aid available. Certificate recognised by employers across Pakistan.',
            category_id: 5, category_name: 'Course',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(14), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via financial aid',
            duration: '7 months (self-paced)',
            required_skills: ['Basic Computer Literacy', 'Curiosity'],
            eligibility: 'Anyone. Apply for financial aid on Coursera before enrolling.',
            application_link: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
            tags: ['React', 'frontend', 'Meta', 'certificate', 'beginner-friendly'], posted_by: by,
        },
        {
            title: 'Google UX Design Professional Certificate',
            organization: 'Google / Coursera',
            description: 'Learn UX Design from Google\'s own designers through 7 self-paced courses covering design thinking, wireframing, prototyping in Figma, and usability testing. Financial aid available. Designed for beginners — no prior design experience needed.',
            category_id: 5, category_name: 'Course',
            dept_id: 4, dept_name: 'Media Studies',
            deadline: future(18), opp_mode: 'remote', location: 'Online (Coursera)',
            is_paid: false, stipend: 'Free via financial aid',
            duration: '6 months (self-paced)',
            required_skills: ['No prior experience needed'],
            eligibility: 'Open to anyone. Apply for Coursera financial aid.',
            application_link: 'https://www.coursera.org/professional-certificates/google-ux-design',
            tags: ['UX', 'Figma', 'design', 'Google', 'certificate'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 6 — EXCHANGE PROGRAMS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const exchangePrograms = [
        {
            title: 'Erasmus+ Exchange — TU Munich, Germany',
            organization: 'TU Munich & Erasmus+',
            description: 'One semester at TU Munich (top 50 globally for CS/Engineering). Erasmus+ grant covers tuition, EUR 600–800/month living allowance, and return flights. Take courses in AI, robotics, or entrepreneurship. Credits transfer fully to NUST.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(65), opp_mode: 'on-campus', location: 'Munich, Germany',
            is_paid: true, stipend: 'EUR 600–800/month + travel',
            duration: '1 semester (5 months)',
            required_skills: ['IELTS 6.0+ or TOEFL 80+'],
            eligibility: '3rd or 4th year BS. CGPA ≥ 3.0. Nominated by NUST OAA office.',
            application_link: '',
            tags: ['Germany', 'Erasmus', 'Europe', 'exchange', 'fully-funded'], posted_by: by,
        },
        {
            title: 'AIT Thailand Semester Exchange Program',
            organization: 'Asian Institute of Technology (AIT)',
            description: 'Semester exchange in Bangkok at AIT, which has students from 50+ countries. NUST waives home tuition while you pay discounted AIT fees. Strong research collaboration opportunities with AIT faculty in Engineering and Environment.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(55), opp_mode: 'on-campus', location: 'Bangkok, Thailand',
            is_paid: false, stipend: 'Tuition waiver at NUST',
            duration: '1 semester',
            required_skills: ['IELTS 5.5+'],
            eligibility: 'BS 3rd year+. Good academic standing (no F grade).',
            application_link: '',
            tags: ['Asia', 'Thailand', 'exchange', 'engineering'], posted_by: by,
        },
        {
            title: 'South Korea POSTECH Exchange Program',
            organization: 'POSTECH (Pohang University of Science & Technology)',
            description: 'POSTECH, ranked among Asia\'s top 10 science and technology universities, offers a one-semester exchange for CS and EE students. Students take advanced courses in semiconductor engineering, AI, or bioinformatics. Dormitory accommodation provided on campus.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(70), opp_mode: 'on-campus', location: 'Pohang, South Korea',
            is_paid: false, stipend: 'Dorm provided (tuition waiver at NUST)',
            duration: '1 semester',
            required_skills: ['English Proficiency', 'Strong Academic Standing'],
            eligibility: 'BS 3rd year+ in CS or EE. Apply through NUST OAA.',
            application_link: '',
            tags: ['South-Korea', 'Asia', 'POSTECH', 'engineering'], posted_by: by,
        },
        {
            title: 'Japan JASSO Short-Term Exchange — Kyoto University',
            organization: 'Japan Student Services Organisation (JASSO)',
            description: 'JASSO\'s short-term student exchange sends NUST students to Kyoto University for one semester. Includes a JPY 80,000/month stipend from JASSO. Kyoto University is one of Japan\'s most prestigious institutions, with world-class research in CS, robotics, and physics.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(58), opp_mode: 'on-campus', location: 'Kyoto, Japan',
            is_paid: true, stipend: 'JPY 80,000/month from JASSO',
            duration: '1 semester',
            required_skills: ['TOEFL 72+ or IELTS 5.5+', 'Japanese A1 (preferred)'],
            eligibility: 'BS 3rd year+ in CS/EE/Sciences. CGPA ≥ 3.2.',
            application_link: '',
            tags: ['Japan', 'JASSO', 'Kyoto', 'stipend', 'exchange'], posted_by: by,
        },
        {
            title: 'China Scholarship Council (CSC) Program',
            organization: 'China Scholarship Council / Chinese Universities',
            description: 'Full scholarship for Pakistani students to study at top Chinese universities (Tsinghua, Peking, Fudan, USTC). Covers tuition, accommodation, health insurance, and a monthly stipend. Available for Bachelor\'s, Master\'s, and PhD programmes.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(48), opp_mode: 'on-campus', location: 'Beijing / Shanghai / Hefei, China',
            is_paid: true, stipend: 'CNY 2,500–3,500/month + tuition + dorm',
            duration: '4 years (BS) / 2–3 years (Master\'s) / 3–4 years (PhD)',
            required_skills: ['Academic Excellence', 'English or Chinese Proficiency'],
            eligibility: 'Pakistani citizens under 35. CGPA ≥ 3.0. Apply through HEC.',
            application_link: 'https://www.hec.gov.pk/csc',
            tags: ['China', 'fully-funded', 'Tsinghua', 'BS', 'masters', 'PhD'], posted_by: by,
        },
        {
            title: 'Turkey Mevlana Exchange Programme',
            organization: 'Council of Higher Education Turkey (YÖK)',
            description: 'The Mevlana Exchange Programme enables students to study for one or two semesters at partner Turkish universities (METU, ITU, Bogazici). Turkey\'s top universities have excellent engineering and social science departments. Credit transfer to NUST is fully recognised.',
            category_id: 6, category_name: 'Exchange Program',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(44), opp_mode: 'on-campus', location: 'Ankara / Istanbul, Turkey',
            is_paid: false, stipend: 'Tuition waiver at NUST',
            duration: '1–2 semesters',
            required_skills: ['IELTS 5.5+ or Turkish A2 (for Turkish-medium courses)'],
            eligibility: 'BS 2nd year+ in any discipline. CGPA ≥ 2.5.',
            application_link: '',
            tags: ['Turkey', 'METU', 'Bogazici', 'Europe', 'exchange'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 7 — COMPETITIONS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const competitions = [
        {
            title: 'ICPC Asia Regionals 2025 — Lahore Site',
            organization: 'ACM-ICPC',
            description: 'Teams of 3 solve algorithmic problems in 5 hours at the prestigious ACM-ICPC Asia Regionals. Top teams qualify for the ICPC World Finals. NUST ACM Chapter provides practice sessions and travel grants for selected teams.',
            category_id: 7, category_name: 'Competition',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(7), opp_mode: 'on-campus', location: 'UET Lahore',
            is_paid: false, stipend: 'Travel grant for top 3 NUST teams',
            duration: '1-day competition',
            required_skills: ['Competitive Programming', 'Algorithms', 'C++ or Java'],
            eligibility: 'Full-time students. Teams of exactly 3.',
            application_link: '',
            tags: ['competitive-programming', 'algorithms', 'ICPC', 'world-finals'], posted_by: by,
        },
        {
            title: 'Microsoft Imagine Cup 2025',
            organization: 'Microsoft',
            description: 'World\'s premier student technology competition. Build a tech solution addressing a global challenge (healthcare, sustainability, education). National → Regional → World Finals (USD 100,000 prize). Top Pakistani teams have won global rounds before.',
            category_id: 7, category_name: 'Competition',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(40), opp_mode: 'remote', location: 'Online → World Finals (Seattle)',
            is_paid: true, stipend: 'USD 100,000 (World Finals winner)',
            duration: '3 months (qualifying) + Finals',
            required_skills: ['Azure', 'AI/ML', 'Pitching', 'Any Tech Stack'],
            eligibility: 'Enrolled students aged 18+. Teams of 1–3.',
            application_link: 'https://imaginecup.microsoft.com',
            tags: ['global', 'Azure', 'AI', 'prize', 'impact'], posted_by: by,
        },
        {
            title: 'NUST Incubator Business Plan Competition',
            organization: 'NUST Technology Incubator (NIC)',
            description: 'Annual competition where NUST teams pitch startup ideas to VCs and industry experts. Top 10 teams get free co-working space for 3 months. Winner receives PKR 2,000,000 seed funding from NIC and access to mentorship network.',
            category_id: 7, category_name: 'Competition',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(25), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: true, stipend: 'PKR 2,000,000 seed funding (winner)',
            duration: '2-day final',
            required_skills: ['Business Planning', 'Financial Modeling', 'Pitching'],
            eligibility: 'NUST students only. Teams of 2–5.',
            application_link: '',
            tags: ['startup', 'seed-funding', 'entrepreneurship', 'NIC'], posted_by: by,
        },
        {
            title: 'CFA Institute Research Challenge — Pakistan',
            organization: 'CFA Society Pakistan',
            description: 'Annual global competition where university teams produce a professional equity research report on an assigned Pakistani listed company and present findings to a jury of CFA Charterholders. Winning team represents Pakistan at the global CFA Research Challenge.',
            category_id: 7, category_name: 'Competition',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(33), opp_mode: 'on-campus', location: 'Karachi / Islamabad',
            is_paid: false, stipend: 'Global winner: prestige + CFA resources',
            duration: '3 months (research) + 1-day final',
            required_skills: ['Financial Modelling', 'DCF Valuation', 'Report Writing', 'Excel'],
            eligibility: 'University students in Finance, Economics, or Business. Teams of 3–5.',
            application_link: 'https://cfasociety.org.pk/research-challenge',
            tags: ['finance', 'equity-research', 'CFA', 'global'], posted_by: by,
        },
        {
            title: 'Ericsson Innovation Awards',
            organization: 'Ericsson',
            description: 'Ericsson\'s annual global student competition challenges teams to develop innovative solutions around 5G and IoT. Pakistani university teams have placed in the global top 20. Finalists present to Ericsson leadership and receive mentorship from Ericsson engineers.',
            category_id: 7, category_name: 'Competition',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(28), opp_mode: 'remote', location: 'Online → Global Finals (Stockholm)',
            is_paid: true, stipend: 'EUR 10,000 (Global winner)',
            duration: '6 months',
            required_skills: ['5G', 'IoT', 'Innovation', 'Prototype Development'],
            eligibility: 'University students worldwide. Teams of 3–5.',
            application_link: 'https://www.ericsson.com/en/careers/university/innovation-awards',
            tags: ['5G', 'IoT', 'Ericsson', 'global', 'telecom'], posted_by: by,
        },
        {
            title: 'P&G CEO Challenge',
            organization: 'Procter & Gamble Pakistan',
            description: 'P&G\'s flagship university competition challenges teams to solve a real business problem faced by one of P&G\'s brands in Pakistan. Round 1 is online submission; finals are held at P&G HQ. Winners receive PKR 100,000 + fast-track interview for internship.',
            category_id: 7, category_name: 'Competition',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(15), opp_mode: 'hybrid', location: 'Karachi (Finals)',
            is_paid: true, stipend: 'PKR 100,000 (winners) + internship fast-track',
            duration: '4 weeks',
            required_skills: ['Case Analysis', 'Strategy', 'Presentation', 'Teamwork'],
            eligibility: 'Penultimate or final year students. Any discipline. Teams of 4.',
            application_link: 'https://www.pg.com.pk/careers',
            tags: ['FMCG', 'business-case', 'strategy', 'P&G', 'internship'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  CATEGORY 8 — WORKSHOPS  (6 entries)
    // ─────────────────────────────────────────────────────────────────────────
    const workshops = [
        {
            title: 'GDSC NUST — Google Technologies Workshop Series',
            organization: 'Google Developer Student Clubs (GDSC)',
            description: 'GDSC NUST runs a semester-long workshop series covering Flutter, Firebase, Google Cloud, and TensorFlow Lite. Each session is 3 hours with hands-on labs. Attendees build and deploy a real project by the end of the series. Google swag for top contributors.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(5), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'Free',
            duration: '8 sessions (1 per week)',
            required_skills: ['Basic Programming'],
            eligibility: 'Open to all NUST students.',
            application_link: '',
            tags: ['Google', 'Flutter', 'Firebase', 'cloud', 'free'], posted_by: by,
        },
        {
            title: 'AWS Cloud Fundamentals Technical Workshop',
            organization: 'Amazon Web Services (AWS)',
            description: 'One-day intensive workshop by AWS Solutions Architects covering EC2, S3, Lambda, and RDS. Attendees get USD 50 AWS credits to follow along in live labs. Certificate of attendance issued by AWS. Workshop held at universities — register your NUST campus.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 1, dept_name: 'Computer Science',
            deadline: future(10), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'Free + USD 50 AWS credits',
            duration: '1 day (8 hours)',
            required_skills: ['Basic Linux', 'Networking Concepts'],
            eligibility: 'Any university student. Bring a laptop.',
            application_link: 'https://aws.amazon.com/training/events',
            tags: ['AWS', 'cloud', 'labs', 'free', 'certificate'], posted_by: by,
        },
        {
            title: 'IEEE Pakistan — Robotics & Embedded Systems Workshop',
            organization: 'IEEE Pakistan Section',
            description: 'Two-day hands-on workshop on robot programming with Arduino and ROS (Robot Operating System). Participants build a line-following robot and a simple robotic arm controller. IEEE membership not required. Components provided on-site.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 3, dept_name: 'Electrical Engineering',
            deadline: future(7), opp_mode: 'on-campus', location: 'NUST SEECS, Islamabad',
            is_paid: false, stipend: 'Free (limited to 40 seats)',
            duration: '2 days (16 hours total)',
            required_skills: ['Basic Electronics', 'C Programming'],
            eligibility: 'EE, Mechatronics, or CS students. 2nd year and above.',
            application_link: '',
            tags: ['robotics', 'Arduino', 'ROS', 'IEEE', 'embedded'], posted_by: by,
        },
        {
            title: 'UN Youth Forum — SDGs & Leadership Workshop',
            organization: 'United Nations Pakistan',
            description: 'Full-day UN-facilitated workshop for university students on the Sustainable Development Goals (SDGs), advocacy skills, and youth leadership. Participants develop action plans for their campuses. Attendance certificate from UNDP Pakistan issued.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 6, dept_name: 'Psychology',
            deadline: future(12), opp_mode: 'on-campus', location: 'Islamabad',
            is_paid: false, stipend: 'Free',
            duration: '1 day (8 hours)',
            required_skills: ['Public Speaking', 'Leadership Interest'],
            eligibility: 'All Pakistani university students. Apply early — limited to 60 seats.',
            application_link: 'https://www.pk.undp.org/youth',
            tags: ['UN', 'SDGs', 'leadership', 'advocacy', 'certificate'], posted_by: by,
        },
        {
            title: 'Startup Weekend NUST — 54-Hour Startup Bootcamp',
            organization: 'Techstars / NUST Entrepreneurship Centre',
            description: 'The world\'s leading startup event, coming to NUST. Pitch an idea on Friday night, form a team, validate with real customers, and demo a working MVP to judges on Sunday evening. Coaches from Google, Careem, and Systems Limited mentor teams throughout the weekend.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(6), opp_mode: 'on-campus', location: 'NUST, Islamabad',
            is_paid: false, stipend: 'PKR 500 registration fee only',
            duration: '54 hours (Fri evening – Sun evening)',
            required_skills: ['Entrepreneurial Mindset', 'Any Skill (Design / Code / Business)'],
            eligibility: 'Open to all university students and recent graduates.',
            application_link: 'https://startupweekend.org',
            tags: ['startup', 'entrepreneurship', 'MVP', 'Techstars', 'Careem'], posted_by: by,
        },
        {
            title: 'Accenture Future Talent — Digital Skills Workshop',
            organization: 'Accenture Pakistan',
            description: 'Accenture\'s half-day workshop introduces students to Agile project management, data-driven decision making, and digital transformation strategy. Run by Accenture Managing Directors. Participants complete a mini case study and receive a digital badge on LinkedIn. Potential to fast-track into Accenture\'s campus hiring.',
            category_id: 8, category_name: 'Workshop',
            dept_id: 2, dept_name: 'Business Administration',
            deadline: future(13), opp_mode: 'on-campus', location: 'Karachi / Islamabad',
            is_paid: false, stipend: 'Free (LinkedIn digital badge)',
            duration: '4 hours',
            required_skills: ['Business Basics', 'Communication'],
            eligibility: 'Penultimate and final year students. All disciplines.',
            application_link: 'https://www.accenture.com/pk-en/careers/students',
            tags: ['Accenture', 'Agile', 'digital', 'LinkedIn-badge', 'hiring'], posted_by: by,
        },
    ];

    // ─────────────────────────────────────────────────────────────────────────
    //  Insert all opportunities
    // ─────────────────────────────────────────────────────────────────────────
    const all = await Opportunity.insertMany([
        ...internships, ...scholarships, ...hackathons,
        ...research, ...courses, ...exchangePrograms,
        ...competitions, ...workshops,
    ]);
    console.log(`✔ Created ${all.length} opportunities`);

    // Notify demo student of all new opportunities
    const notifs = all.map(o => ({
        user_id: student._id,
        opp_id:  o._id,
        message: `New opportunity posted: ${o.title}`,
        is_read: false,
    }));
    await Notification.insertMany(notifs);
    console.log(`✔ Created ${notifs.length} notifications`);

    const counts = {};
    all.forEach(o => { counts[o.category_name] = (counts[o.category_name] || 0) + 1; });
    console.log('\n📊 Opportunities per category:');
    Object.entries(counts).forEach(([cat, n]) => console.log(`   ${cat.padEnd(20)} ${n}`));

    console.log('\n✅ Seed complete!');
    console.log('   Admin   → admin@campus.edu      / admin123');
    console.log('   Student → student@seecs.edu.pk  / student123');

    await mongoose.disconnect();
}

seed().catch(err => { console.error('Seed failed:', err); process.exit(1); });
